import * as SecureStore from 'expo-secure-store';
import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

export type LanguageCode = 'en' | 'sq' | 'it' | 'de';

interface LanguageOption {
  code: LanguageCode;
  label: string;
}

const LANGUAGE_STORAGE_KEY = 'app_language';

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English' },
  { code: 'sq', label: 'Shqip / Albanian' },
  { code: 'it', label: 'Italiano / Italian' },
  { code: 'de', label: 'Deutsch / German' },
];

const en = {
  'nav.home': 'Home',
  'nav.attendance': 'Attendance',
  'nav.requests': 'Requests',
  'nav.payroll': 'Payroll',
  'nav.updates': 'Updates',
  'nav.profile': 'Profile',
  'common.cancel': 'Cancel',
  'common.current': 'Current',
  'common.new': 'new',
  'common.notAvailable': 'N/A',
  'common.notAssigned': 'Not assigned',
  'common.day': 'day',
  'common.days': 'days',
  'common.tryAgain': 'Try again',
  'common.loading': 'Loading...',
  'home.hello': 'Hello,',
  'home.attendance': 'Attendance',
  'home.today': 'Today',
  'home.checkedInAt': 'Checked in at',
  'home.notCheckedIn': 'Not checked in',
  'home.leaveBalance': 'Leave Balance',
  'home.noActiveLeaveBalances': 'No active leave balances',
  'home.latestPayroll': 'Latest Payroll',
  'home.noPayrollData': 'No payroll data available',
  'home.announcements': 'Announcements',
  'attendance.title': 'Attendance',
  'attendance.clock': 'Clock',
  'attendance.clockIn': 'Clock In',
  'attendance.clockOut': 'Clock Out',
  'attendance.actionBlocked': 'Action Blocked',
  'attendance.noActionAvailable': 'No Action Available',
  'attendance.loadingState': 'Loading attendance state...',
  'attendance.blockedHint': 'Attendance action is currently blocked.',
  'attendance.unavailableReason': 'Attendance action is currently unavailable.',
  'attendance.clockInHint': 'Tap to record check-in',
  'attendance.clockOutHint': 'Tap to record check-out',
  'attendance.completedHint': 'Attendance is already completed for today.',
  'attendance.submitting': 'Submitting attendance...',
  'attendance.qrRequired': 'QR required',
  'attendance.gpsRequired': 'GPS required',
  'attendance.clockHint': 'Tap the button above to clock in or out and track your attendance.',
  'attendance.todayRecords': 'Today Records',
  'attendance.dayStatus': 'Day Status',
  'attendance.workedMinutes': 'Worked Minutes',
  'attendance.present': 'Present',
  'attendance.absent': 'Absent',
  'attendance.late': 'Late',
  'attendance.halfDay': 'Half Day',
  'attendance.leaveHoliday': 'Leave/Holiday',
  'attendance.noCheckout': 'No Checkout',
  'attendance.pending': 'Pending',
  'attendance.loadingCalendar': 'Loading calendar...',
  'attendance.status': 'Status',
  'attendance.scanSiteQr': 'Scan Site QR',
  'attendance.scanSiteQrHint': 'Point your camera at the site QR code to continue.',
  'attendance.webQrUnavailable': 'Camera scanning is unavailable on web. Paste the QR token to continue.',
  'attendance.pasteQrToken': 'Paste QR token',
  'attendance.useToken': 'Use Token',
  'attendance.preparingCamera': 'Preparing camera...',
  'attendance.cameraPermission': 'Camera permission is required to scan the attendance QR code.',
  'attendance.allowCamera': 'Allow Camera',
  'attendance.alignQr': 'Align the QR code within the frame',
  'requests.title': 'Leave Requests',
  'requests.yourBalance': 'YOUR BALANCE',
  'requests.requestHistory': 'REQUEST HISTORY',
  'requests.noHistory': 'No request history found.',
  'requests.requestLeave': 'Request Leave',
  'requests.leaveType': 'Leave Type',
  'requests.selectType': 'Select Type',
  'requests.startDate': 'Start Date',
  'requests.endDate': 'End Date',
  'requests.medicalReportRequired': 'Medical Report ID (Required)',
  'requests.enterDocumentId': 'Enter document ID...',
  'requests.noteOptional': 'Note (Optional)',
  'requests.addNote': 'Add a note...',
  'requests.submitRequest': 'Submit Request',
  'requests.cancelRequest': 'Cancel Request',
  'requests.reason': 'Reason',
  'requests.noteFromApprover': 'Note from approver',
  'requests.vacation': 'Vacation',
  'requests.sickLeave': 'Sick Leave',
  'requests.personal': 'Personal',
  'requests.unpaid': 'Unpaid',
  'requests.maternity': 'Maternity',
  'requests.paternity': 'Paternity',
  'requests.other': 'Other',
  'requests.approved': 'Approved',
  'requests.pending': 'Pending',
  'requests.rejected': 'Rejected',
  'requests.cancelled': 'Cancelled',
  'payroll.title': 'Payroll',
  'payroll.notIncluded': 'Payroll not included',
  'payroll.upgradeText': 'Payroll is available on Growth and Professional plans. Upgrade at worknest.com.',
  'payroll.current': 'Current',
  'payroll.netPay': 'Net pay',
  'payroll.cardHint': 'Tap to view your payroll breakdown and download the payslip PDF.',
  'payroll.details': 'Payroll Details',
  'payroll.loadingDetails': 'Loading payroll details...',
  'payroll.downloadPdf': 'Download payslip PDF',
  'payroll.downloading': 'Downloading...',
  'payroll.pdfUnavailable': 'PDF not available - payroll must be calculated before downloading.',
  'updates.title': 'Announcements',
  'updates.noAnnouncements': 'No announcements yet',
  'updates.announcement': 'Announcement',
  'updates.important': 'Important',
  'updates.general': 'General',
  'updates.markAsRead': 'Mark as read',
  'updates.justNow': 'just now',
  'updates.yesterday': 'yesterday',
  'updates.minutesAgo': 'm ago',
  'updates.hoursAgo': 'h ago',
  'updates.daysAgo': 'days ago',
  'updates.monthAgo': 'month ago',
  'updates.monthsAgo': 'months ago',
  'profile.employmentInformation': 'Employment Information',
  'profile.department': 'Department',
  'profile.site': 'Site',
  'profile.contract': 'Contract',
  'profile.contractType': 'Contract Type',
  'profile.contractStatus': 'Contract Status',
  'profile.contractStartDate': 'Contract Start Date',
  'profile.contractEndDate': 'Contract End Date',
  'profile.language': 'Language',
  'profile.selectLanguage': 'Select Language',
  'profile.currentLanguage': 'Current language',
  'profile.changePassword': 'Change Password',
  'profile.changePasswordSubtitle': 'Update your password',
  'profile.logout': 'Log Out',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.welcomeBack': 'Welcome Back',
  'auth.signInToContinue': 'Sign in to continue',
  'auth.forgotPassword': 'Forgot password?',
  'auth.login': 'Login',
  'auth.loggingIn': 'Logging in...',
} as const;

type TranslationKey = keyof typeof en;
type TranslationMap = Record<TranslationKey, string>;

const translations: Record<LanguageCode, TranslationMap> = {
  en,
  sq: {
    ...en,
    'nav.home': 'Kreu',
    'nav.attendance': 'Prezenca',
    'nav.requests': 'Kerkesat',
    'nav.payroll': 'Pagat',
    'nav.updates': 'Njoftimet',
    'nav.profile': 'Profili',
    'common.cancel': 'Anulo',
    'common.current': 'Aktuale',
    'common.new': 'te reja',
    'common.notAssigned': 'I pacaktuar',
    'common.day': 'dite',
    'common.days': 'dite',
    'common.tryAgain': 'Provo perseri',
    'home.hello': 'Pershendetje,',
    'home.attendance': 'Prezenca',
    'home.today': 'Sot',
    'home.checkedInAt': 'Hyrje ne',
    'home.notCheckedIn': 'Nuk ke bere hyrje',
    'home.leaveBalance': 'Bilanci i pushimeve',
    'home.noActiveLeaveBalances': 'Nuk ka bilance aktive',
    'home.latestPayroll': 'Paga e fundit',
    'home.noPayrollData': 'Nuk ka te dhena page',
    'home.announcements': 'Njoftime',
    'attendance.title': 'Prezenca',
    'attendance.clock': 'Regjistro',
    'attendance.clockIn': 'Regjistro hyrjen',
    'attendance.clockOut': 'Regjistro daljen',
    'attendance.actionBlocked': 'Veprim i bllokuar',
    'attendance.noActionAvailable': 'Nuk ka veprim',
    'attendance.loadingState': 'Duke ngarkuar gjendjen...',
    'attendance.blockedHint': 'Veprimi i prezences eshte i bllokuar.',
    'attendance.unavailableReason': 'Veprimi i prezences nuk eshte i disponueshem.',
    'attendance.clockInHint': 'Prek per te regjistruar hyrjen',
    'attendance.clockOutHint': 'Prek per te regjistruar daljen',
    'attendance.completedHint': 'Prezenca per sot ka perfunduar.',
    'attendance.submitting': 'Duke derguar prezencen...',
    'attendance.qrRequired': 'Kerkohet QR',
    'attendance.gpsRequired': 'Kerkohet GPS',
    'attendance.clockHint': 'Prek butonin me siper per te regjistruar prezencen.',
    'attendance.todayRecords': 'Regjistrimet e sotme',
    'attendance.dayStatus': 'Statusi i dites',
    'attendance.workedMinutes': 'Minuta pune',
    'attendance.present': 'Prezent',
    'attendance.absent': 'Mungon',
    'attendance.late': 'Me vonese',
    'attendance.halfDay': 'Gjysme dite',
    'attendance.leaveHoliday': 'Pushim/Feste',
    'attendance.noCheckout': 'Pa dalje',
    'attendance.pending': 'Ne pritje',
    'attendance.loadingCalendar': 'Duke ngarkuar kalendarin...',
    'attendance.status': 'Statusi',
    'attendance.scanSiteQr': 'Skano QR e vendit',
    'attendance.scanSiteQrHint': 'Drejto kameren te kodi QR i vendit.',
    'attendance.webQrUnavailable': 'Skanimi me kamere nuk eshte i disponueshem ne web. Vendos tokenin QR.',
    'attendance.pasteQrToken': 'Vendos tokenin QR',
    'attendance.useToken': 'Perdor tokenin',
    'attendance.preparingCamera': 'Duke pergatitur kameren...',
    'attendance.cameraPermission': 'Leja e kameres kerkohet per skanim.',
    'attendance.allowCamera': 'Lejo kameren',
    'attendance.alignQr': 'Vendos QR brenda kornizes',
    'requests.title': 'Kerkesa pushimi',
    'requests.yourBalance': 'BILANCI YT',
    'requests.requestHistory': 'HISTORIKU I KERKESAVE',
    'requests.noHistory': 'Nuk u gjet historik kerkesash.',
    'requests.requestLeave': 'Kerko pushim',
    'requests.leaveType': 'Lloji i pushimit',
    'requests.selectType': 'Zgjidh llojin',
    'requests.startDate': 'Data e fillimit',
    'requests.endDate': 'Data e perfundimit',
    'requests.medicalReportRequired': 'ID e raportit mjekesor (E detyrueshme)',
    'requests.enterDocumentId': 'Vendos ID dokumenti...',
    'requests.noteOptional': 'Shenim (Opsional)',
    'requests.addNote': 'Shto shenim...',
    'requests.submitRequest': 'Dergo kerkesen',
    'requests.cancelRequest': 'Anulo kerkesen',
    'requests.reason': 'Arsyeja',
    'requests.noteFromApprover': 'Shenim nga aprovuesi',
    'requests.vacation': 'Pushim',
    'requests.sickLeave': 'Raport mjekesor',
    'requests.personal': 'Personal',
    'requests.unpaid': 'Pa pagese',
    'requests.maternity': 'Leje lindjeje',
    'requests.paternity': 'Leje prinderore',
    'requests.other': 'Tjeter',
    'requests.approved': 'Aprovuar',
    'requests.pending': 'Ne pritje',
    'requests.rejected': 'Refuzuar',
    'requests.cancelled': 'Anuluar',
    'payroll.title': 'Pagat',
    'payroll.notIncluded': 'Pagat nuk perfshihen',
    'payroll.upgradeText': 'Pagat jane te disponueshme ne planet Growth dhe Professional. Perditeso ne worknest.com.',
    'payroll.netPay': 'Paga neto',
    'payroll.cardHint': 'Prek per te pare detajet e pages dhe per te shkarkuar PDF.',
    'payroll.details': 'Detajet e pages',
    'payroll.loadingDetails': 'Duke ngarkuar detajet...',
    'payroll.downloadPdf': 'Shkarko PDF e pages',
    'payroll.downloading': 'Duke shkarkuar...',
    'payroll.pdfUnavailable': 'PDF nuk eshte i disponueshem - paga duhet llogaritur para shkarkimit.',
    'updates.title': 'Njoftime',
    'updates.noAnnouncements': 'Nuk ka njoftime ende',
    'updates.announcement': 'Njoftim',
    'updates.important': 'E rendesishme',
    'updates.general': 'E pergjithshme',
    'updates.markAsRead': 'Sheno si lexuar',
    'updates.justNow': 'tani',
    'updates.yesterday': 'dje',
    'updates.daysAgo': 'dite me pare',
    'updates.monthAgo': 'muaj me pare',
    'updates.monthsAgo': 'muaj me pare',
    'profile.employmentInformation': 'Informacioni i punesimit',
    'profile.department': 'Departamenti',
    'profile.site': 'Lokacioni',
    'profile.contract': 'Kontrata',
    'profile.language': 'Gjuha',
    'profile.selectLanguage': 'Zgjidh gjuhen',
    'profile.currentLanguage': 'Gjuha aktuale',
    'profile.changePassword': 'Ndrysho fjalekalimin',
    'profile.changePasswordSubtitle': 'Perditeso fjalekalimin',
    'profile.logout': 'Dil',
    'auth.email': 'Email',
    'auth.password': 'Fjalekalimi',
    'auth.welcomeBack': 'Mire se u ktheve',
    'auth.signInToContinue': 'Hyr per te vazhduar',
    'auth.forgotPassword': 'Harruat fjalekalimin?',
    'auth.login': 'Hyr',
    'auth.loggingIn': 'Duke hyre...',
  },
  it: {
    ...en,
    'nav.home': 'Home',
    'nav.attendance': 'Presenze',
    'nav.requests': 'Richieste',
    'nav.payroll': 'Paghe',
    'nav.updates': 'Aggiornamenti',
    'nav.profile': 'Profilo',
    'common.cancel': 'Annulla',
    'common.current': 'Corrente',
    'common.new': 'nuovi',
    'common.notAssigned': 'Non assegnato',
    'common.notAvailable': 'N/D',
    'common.day': 'giorno',
    'common.days': 'giorni',
    'common.tryAgain': 'Riprova',
    'home.hello': 'Ciao,',
    'home.attendance': 'Presenze',
    'home.today': 'Oggi',
    'home.checkedInAt': 'Entrata alle',
    'home.notCheckedIn': 'Non entrato',
    'home.leaveBalance': 'Saldo ferie',
    'home.noActiveLeaveBalances': 'Nessun saldo ferie attivo',
    'home.latestPayroll': 'Ultima busta paga',
    'home.noPayrollData': 'Nessun dato paghe disponibile',
    'home.announcements': 'Annunci',
    'attendance.title': 'Presenze',
    'attendance.clock': 'Timbratura',
    'attendance.clockIn': 'Entrata',
    'attendance.clockOut': 'Uscita',
    'attendance.actionBlocked': 'Azione bloccata',
    'attendance.noActionAvailable': 'Nessuna azione',
    'attendance.loadingState': 'Caricamento stato presenze...',
    'attendance.blockedHint': 'Azione presenze bloccata.',
    'attendance.unavailableReason': 'Azione presenze non disponibile.',
    'attendance.clockInHint': 'Tocca per registrare entrata',
    'attendance.clockOutHint': 'Tocca per registrare uscita',
    'attendance.completedHint': 'Presenza gia completata per oggi.',
    'attendance.submitting': 'Invio presenza...',
    'attendance.qrRequired': 'QR richiesto',
    'attendance.gpsRequired': 'GPS richiesto',
    'attendance.clockHint': 'Tocca il pulsante sopra per registrare entrata o uscita.',
    'attendance.todayRecords': 'Registri di oggi',
    'attendance.dayStatus': 'Stato giorno',
    'attendance.workedMinutes': 'Minuti lavorati',
    'attendance.present': 'Presente',
    'attendance.absent': 'Assente',
    'attendance.late': 'In ritardo',
    'attendance.halfDay': 'Mezza giornata',
    'attendance.leaveHoliday': 'Ferie/Festivo',
    'attendance.noCheckout': 'Senza uscita',
    'attendance.pending': 'In attesa',
    'attendance.loadingCalendar': 'Caricamento calendario...',
    'attendance.status': 'Stato',
    'attendance.scanSiteQr': 'Scansiona QR sede',
    'attendance.scanSiteQrHint': 'Punta la fotocamera sul codice QR della sede.',
    'attendance.webQrUnavailable': 'La scansione camera non e disponibile sul web. Incolla il token QR.',
    'attendance.pasteQrToken': 'Incolla token QR',
    'attendance.useToken': 'Usa token',
    'attendance.preparingCamera': 'Preparazione camera...',
    'attendance.cameraPermission': 'Serve il permesso camera per scansionare il QR.',
    'attendance.allowCamera': 'Consenti camera',
    'attendance.alignQr': 'Allinea il QR dentro il riquadro',
    'requests.title': 'Richieste ferie',
    'requests.yourBalance': 'IL TUO SALDO',
    'requests.requestHistory': 'STORICO RICHIESTE',
    'requests.noHistory': 'Nessuno storico richieste trovato.',
    'requests.requestLeave': 'Richiedi ferie',
    'requests.leaveType': 'Tipo ferie',
    'requests.selectType': 'Seleziona tipo',
    'requests.startDate': 'Data inizio',
    'requests.endDate': 'Data fine',
    'requests.medicalReportRequired': 'ID certificato medico (Obbligatorio)',
    'requests.enterDocumentId': 'Inserisci ID documento...',
    'requests.noteOptional': 'Nota (Opzionale)',
    'requests.addNote': 'Aggiungi nota...',
    'requests.submitRequest': 'Invia richiesta',
    'requests.cancelRequest': 'Annulla richiesta',
    'requests.reason': 'Motivo',
    'requests.noteFromApprover': 'Nota dell approvatore',
    'requests.vacation': 'Ferie',
    'requests.sickLeave': 'Malattia',
    'requests.personal': 'Personale',
    'requests.unpaid': 'Non retribuito',
    'requests.maternity': 'Maternita',
    'requests.paternity': 'Paternita',
    'requests.other': 'Altro',
    'requests.approved': 'Approvata',
    'requests.pending': 'In attesa',
    'requests.rejected': 'Rifiutata',
    'requests.cancelled': 'Annullata',
    'payroll.title': 'Paghe',
    'payroll.notIncluded': 'Paghe non incluse',
    'payroll.upgradeText': 'Le paghe sono disponibili nei piani Growth e Professional. Aggiorna su worknest.com.',
    'payroll.current': 'Corrente',
    'payroll.netPay': 'Netto',
    'payroll.cardHint': 'Tocca per vedere il dettaglio paga e scaricare il PDF.',
    'payroll.details': 'Dettagli paga',
    'payroll.loadingDetails': 'Caricamento dettagli paga...',
    'payroll.downloadPdf': 'Scarica PDF busta paga',
    'payroll.downloading': 'Download...',
    'payroll.pdfUnavailable': 'PDF non disponibile - la paga deve essere calcolata prima del download.',
    'updates.title': 'Annunci',
    'updates.noAnnouncements': 'Nessun annuncio',
    'updates.announcement': 'Annuncio',
    'updates.important': 'Importante',
    'updates.general': 'Generale',
    'updates.markAsRead': 'Segna come letto',
    'updates.justNow': 'ora',
    'updates.yesterday': 'ieri',
    'updates.daysAgo': 'giorni fa',
    'updates.monthAgo': 'mese fa',
    'updates.monthsAgo': 'mesi fa',
    'profile.employmentInformation': 'Informazioni lavorative',
    'profile.department': 'Reparto',
    'profile.site': 'Sede',
    'profile.contract': 'Contratto',
    'profile.language': 'Lingua',
    'profile.selectLanguage': 'Seleziona lingua',
    'profile.currentLanguage': 'Lingua corrente',
    'profile.changePassword': 'Cambia password',
    'profile.changePasswordSubtitle': 'Aggiorna la password',
    'profile.logout': 'Esci',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.welcomeBack': 'Bentornato',
    'auth.signInToContinue': 'Accedi per continuare',
    'auth.forgotPassword': 'Password dimenticata?',
    'auth.login': 'Accedi',
    'auth.loggingIn': 'Accesso...',
  },
  de: {
    ...en,
    'nav.home': 'Start',
    'nav.attendance': 'Anwesenheit',
    'nav.requests': 'Anfragen',
    'nav.payroll': 'Gehaltslauf',
    'nav.updates': 'Updates',
    'nav.profile': 'Profil',
    'common.cancel': 'Abbrechen',
    'common.current': 'Aktuell',
    'common.new': 'neu',
    'common.notAssigned': 'Nicht zugewiesen',
    'common.notAvailable': 'N/V',
    'common.day': 'Tag',
    'common.days': 'Tage',
    'common.tryAgain': 'Erneut versuchen',
    'home.hello': 'Hallo,',
    'home.attendance': 'Anwesenheit',
    'home.today': 'Heute',
    'home.checkedInAt': 'Eingecheckt um',
    'home.notCheckedIn': 'Nicht eingecheckt',
    'home.leaveBalance': 'Urlaubssaldo',
    'home.noActiveLeaveBalances': 'Keine aktiven Urlaubssalden',
    'home.latestPayroll': 'Letzte Abrechnung',
    'home.noPayrollData': 'Keine Gehaltsdaten verfugbar',
    'home.announcements': 'Ankundigungen',
    'attendance.title': 'Anwesenheit',
    'attendance.clock': 'Stempeln',
    'attendance.clockIn': 'Einstempeln',
    'attendance.clockOut': 'Ausstempeln',
    'attendance.actionBlocked': 'Aktion blockiert',
    'attendance.noActionAvailable': 'Keine Aktion verfugbar',
    'attendance.loadingState': 'Anwesenheitsstatus wird geladen...',
    'attendance.blockedHint': 'Anwesenheitsaktion ist blockiert.',
    'attendance.unavailableReason': 'Anwesenheitsaktion ist derzeit nicht verfugbar.',
    'attendance.clockInHint': 'Tippen zum Einstempeln',
    'attendance.clockOutHint': 'Tippen zum Ausstempeln',
    'attendance.completedHint': 'Anwesenheit ist heute bereits abgeschlossen.',
    'attendance.submitting': 'Anwesenheit wird gesendet...',
    'attendance.qrRequired': 'QR erforderlich',
    'attendance.gpsRequired': 'GPS erforderlich',
    'attendance.clockHint': 'Tippe auf die Schaltflache oben, um ein- oder auszustempeln.',
    'attendance.todayRecords': 'Heutige Eintrage',
    'attendance.dayStatus': 'Tagesstatus',
    'attendance.workedMinutes': 'Arbeitsminuten',
    'attendance.present': 'Anwesend',
    'attendance.absent': 'Abwesend',
    'attendance.late': 'Verspatet',
    'attendance.halfDay': 'Halber Tag',
    'attendance.leaveHoliday': 'Urlaub/Feiertag',
    'attendance.noCheckout': 'Kein Checkout',
    'attendance.pending': 'Ausstehend',
    'attendance.loadingCalendar': 'Kalender wird geladen...',
    'attendance.status': 'Status',
    'attendance.scanSiteQr': 'Standort-QR scannen',
    'attendance.scanSiteQrHint': 'Richte die Kamera auf den Standort-QR-Code.',
    'attendance.webQrUnavailable': 'Kamerascan ist im Web nicht verfugbar. Fuge den QR-Token ein.',
    'attendance.pasteQrToken': 'QR-Token einfugen',
    'attendance.useToken': 'Token verwenden',
    'attendance.preparingCamera': 'Kamera wird vorbereitet...',
    'attendance.cameraPermission': 'Kamerazugriff ist zum Scannen erforderlich.',
    'attendance.allowCamera': 'Kamera erlauben',
    'attendance.alignQr': 'QR-Code im Rahmen ausrichten',
    'requests.title': 'Urlaubsanfragen',
    'requests.yourBalance': 'DEIN SALDO',
    'requests.requestHistory': 'ANFRAGEVERLAUF',
    'requests.noHistory': 'Kein Anfrageverlauf gefunden.',
    'requests.requestLeave': 'Urlaub beantragen',
    'requests.leaveType': 'Urlaubsart',
    'requests.selectType': 'Art auswahlen',
    'requests.startDate': 'Startdatum',
    'requests.endDate': 'Enddatum',
    'requests.medicalReportRequired': 'Medizinische Bericht-ID (Erforderlich)',
    'requests.enterDocumentId': 'Dokument-ID eingeben...',
    'requests.noteOptional': 'Notiz (Optional)',
    'requests.addNote': 'Notiz hinzufugen...',
    'requests.submitRequest': 'Anfrage senden',
    'requests.cancelRequest': 'Anfrage abbrechen',
    'requests.reason': 'Grund',
    'requests.noteFromApprover': 'Notiz des Genehmigers',
    'requests.vacation': 'Urlaub',
    'requests.sickLeave': 'Krankheit',
    'requests.personal': 'Personlich',
    'requests.unpaid': 'Unbezahlt',
    'requests.maternity': 'Mutterschaft',
    'requests.paternity': 'Vaterschaft',
    'requests.other': 'Andere',
    'requests.approved': 'Genehmigt',
    'requests.pending': 'Ausstehend',
    'requests.rejected': 'Abgelehnt',
    'requests.cancelled': 'Abgebrochen',
    'payroll.title': 'Gehaltslauf',
    'payroll.notIncluded': 'Gehaltslauf nicht enthalten',
    'payroll.upgradeText': 'Gehaltslauf ist in Growth- und Professional-Planen verfugbar. Upgrade auf worknest.com.',
    'payroll.current': 'Aktuell',
    'payroll.netPay': 'Netto',
    'payroll.cardHint': 'Tippen, um Gehaltsdetails anzuzeigen und die PDF herunterzuladen.',
    'payroll.details': 'Gehaltsdetails',
    'payroll.loadingDetails': 'Gehaltsdetails werden geladen...',
    'payroll.downloadPdf': 'Gehalts-PDF herunterladen',
    'payroll.downloading': 'Wird heruntergeladen...',
    'payroll.pdfUnavailable': 'PDF nicht verfugbar - Gehalt muss vor dem Download berechnet werden.',
    'updates.title': 'Ankundigungen',
    'updates.noAnnouncements': 'Noch keine Ankundigungen',
    'updates.announcement': 'Ankundigung',
    'updates.important': 'Wichtig',
    'updates.general': 'Allgemein',
    'updates.markAsRead': 'Als gelesen markieren',
    'updates.justNow': 'gerade eben',
    'updates.yesterday': 'gestern',
    'updates.daysAgo': 'Tage her',
    'updates.monthAgo': 'Monat her',
    'updates.monthsAgo': 'Monate her',
    'profile.employmentInformation': 'Beschaftigungsinformationen',
    'profile.department': 'Abteilung',
    'profile.site': 'Standort',
    'profile.contract': 'Vertrag',
    'profile.language': 'Sprache',
    'profile.selectLanguage': 'Sprache auswahlen',
    'profile.currentLanguage': 'Aktuelle Sprache',
    'profile.changePassword': 'Passwort andern',
    'profile.changePasswordSubtitle': 'Passwort aktualisieren',
    'profile.logout': 'Abmelden',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.welcomeBack': 'Willkommen zuruck',
    'auth.signInToContinue': 'Melde dich an, um fortzufahren',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.login': 'Anmelden',
    'auth.loggingIn': 'Anmeldung...',
  },
};

interface LocalizationContextValue {
  language: LanguageCode;
  languageLabel: string;
  languages: LanguageOption[];
  setLanguage: (language: LanguageCode) => Promise<void>;
  t: (key: TranslationKey) => string;
}

const LocalizationContext = createContext<LocalizationContextValue | null>(null);

function isLanguageCode(value: string | null): value is LanguageCode {
  return LANGUAGES.some((language) => language.code === value);
}

export function LocalizationProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>('en');

  useEffect(() => {
    let isMounted = true;

    SecureStore.getItemAsync(LANGUAGE_STORAGE_KEY)
      .then((storedLanguage) => {
        if (isMounted && isLanguageCode(storedLanguage)) {
          setLanguageState(storedLanguage);
        }
      })
      .catch(() => {
        // Keep English when stored language cannot be read.
      });

    return () => {
      isMounted = false;
    };
  }, []);

  const setLanguage = useCallback(async (nextLanguage: LanguageCode) => {
    setLanguageState(nextLanguage);
    await SecureStore.setItemAsync(LANGUAGE_STORAGE_KEY, nextLanguage);
  }, []);

  const t = useCallback(
    (key: TranslationKey) => translations[language][key] ?? translations.en[key] ?? key,
    [language]
  );

  const value = useMemo(
    () => ({
      language,
      languageLabel: LANGUAGES.find((item) => item.code === language)?.label ?? LANGUAGES[0].label,
      languages: LANGUAGES,
      setLanguage,
      t,
    }),
    [language, setLanguage, t]
  );

  return (
    <LocalizationContext.Provider value={value}>
      {children}
    </LocalizationContext.Provider>
  );
}

export function useLocalization() {
  const context = useContext(LocalizationContext);

  if (!context) {
    throw new Error('useLocalization must be used within LocalizationProvider');
  }

  return context;
}
