import * as SecureStore from 'expo-secure-store';
import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

export type LanguageCode = 'en' | 'sq' | 'it' | 'de';

interface LanguageOption {
  code: LanguageCode;
  label: string;
}

const LANGUAGE_STORAGE_KEY = 'app_language';

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English' },
  { code: 'sq', label: 'Shqip / Albanian' },
  { code: 'it', label: 'Italiano / Italian' },
  { code: 'de', label: 'Deutsch / German' },
];

const en = {
  'nav.home': 'Home',
  'nav.attendance': 'Attendance',
  'nav.requests': 'Requests',
  'nav.payroll': 'Payroll',
  'nav.updates': 'Updates',
  'nav.profile': 'Profile',
  'common.cancel': 'Cancel',
  'common.done': 'Done',
  'common.current': 'Current',
  'common.new': 'new',
  'common.notAvailable': 'N/A',
  'common.notAssigned': 'Not assigned',
  'common.day': 'day',
  'common.days': 'days',
  'common.tryAgain': 'Try again',
  'common.loading': 'Loading...',
  'common.error': 'Error',
  'common.retry': 'Retry',
  'common.success': 'Success',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.email': 'Email',
  'common.role': 'Role',
  'common.jobTitle': 'Job title',
  'common.docs': 'Docs',
  'home.hello': 'Hello,',
  'home.attendance': 'Attendance',
  'home.today': 'Today',
  'home.checkedInAt': 'Checked in at',
  'home.notCheckedIn': 'Not checked in',
  'home.leaveBalance': 'Leave Balance',
  'home.noActiveLeaveBalances': 'No active leave balances',
  'home.latestPayroll': 'Latest Payroll',
  'home.noPayrollData': 'No payroll data available',
  'home.announcements': 'Announcements',
  'attendance.title': 'Attendance',
  'attendance.clock': 'Clock',
  'attendance.clockIn': 'Clock In',
  'attendance.clockOut': 'Clock Out',
  'attendance.actionBlocked': 'Action Blocked',
  'attendance.noActionAvailable': 'No Action Available',
  'attendance.loadingState': 'Loading attendance state...',
  'attendance.blockedHint': 'Attendance action is currently blocked.',
  'attendance.unavailableReason': 'Attendance action is currently unavailable.',
  'attendance.clockInHint': 'Tap to record check-in',
  'attendance.clockOutHint': 'Tap to record check-out',
  'attendance.completedHint': 'Attendance is already completed for today.',
  'attendance.submitting': 'Submitting attendance...',
  'attendance.qrRequired': 'QR required',
  'attendance.gpsRequired': 'GPS required',
  'attendance.clockHint': 'Tap the button above to clock in or out and track your attendance.',
  'attendance.todayRecords': 'Today Records',
  'attendance.dayStatus': 'Day Status',
  'attendance.workedMinutes': 'Worked Minutes',
  'attendance.present': 'Present',
  'attendance.absent': 'Absent',
  'attendance.late': 'Late',
  'attendance.halfDay': 'Half Day',
  'attendance.leaveHoliday': 'Leave/Holiday',
  'attendance.noCheckout': 'No Checkout',
  'attendance.pending': 'Pending',
  'attendance.loadingCalendar': 'Loading calendar...',
  'attendance.status': 'Status',
  'attendance.scanSiteQr': 'Scan Site QR',
  'attendance.scanSiteQrHint': 'Point your camera at the site QR code to continue.',
  'attendance.webQrUnavailable': 'Camera scanning is unavailable on web. Paste the QR token to continue.',
  'attendance.pasteQrToken': 'Paste QR token',
  'attendance.useToken': 'Use Token',
  'attendance.preparingCamera': 'Preparing camera...',
  'attendance.cameraPermission': 'Camera permission is required to scan the attendance QR code.',
  'attendance.allowCamera': 'Allow Camera',
  'attendance.alignQr': 'Align the QR code within the frame',
  'attendance.loadingData': 'Loading attendance data...',
  'attendance.refreshing': 'Refreshing...',
  'attendance.retrySync': 'Retry Sync',
  'attendance.locationUnavailableTitle': 'Location Unavailable',
  'attendance.locationUnavailableMessage': "We couldn't get your location in time. Would you like to retry?",
  'attendance.invalidQr': 'Invalid QR code. Please scan the correct site QR.',
  'attendance.qrValidationFailed': 'QR validation failed. Please try again.',
  'attendance.recordedWithWarnings': 'Attendance recorded with warnings.',
  'attendance.recordedSuccessfully': 'Attendance recorded successfully.',
  'attendance.locationRequiredError': 'Location is required to record attendance for this site.',
  'attendance.locationTimeoutError': "We couldn't get your location in time. Please retry when GPS signal is stable.",
  'attendance.loadError': "We couldn't load attendance. Please retry.",
  'attendance.qrRequiredError': 'Please scan the site QR code before continuing.',
  'attendance.qrInvalidError': 'This QR code is not valid. Please scan the current site QR again.',
  'attendance.qrExpiredError': 'This QR code has expired. Please scan the latest code.',
  'attendance.qrReplayedError': 'This QR code was already used. Please scan a new one.',
  'attendance.qrSiteMismatchError': 'This QR code belongs to a different site. Please scan the QR code at your location.',
  'attendance.invalidLocationError': "We couldn't verify your location. Please try again.",
  'attendance.lowLocationAccuracyError': 'Your GPS signal is too weak. Move to a clearer area and try again.',
  'attendance.outsideGeofenceError': 'You appear to be outside the allowed site area.',
  'attendance.checkinDisabledError': 'Check-in is currently unavailable for this site.',
  'attendance.checkoutDisabledError': 'Check-out is currently unavailable for this site.',
  'attendance.alreadyCheckedOutError': 'You have already completed attendance for today.',
  'attendance.stateInvalidError': 'Your attendance needs review before another action can be recorded.',
  'attendance.employeeInactiveError': 'Your employee account is not active. Please contact your manager.',
  'attendance.companyInactiveError': 'Attendance is currently unavailable for your company.',
  'attendance.siteNotAssignedError': 'No work site is assigned to your profile yet.',
  'attendance.siteDisabledError': 'This site is not active for attendance.',
  'attendance.accessDeniedError': 'You do not have permission to perform this action right now.',
  'attendance.validationError': 'Some required information is missing or invalid. Please try again.',
  'attendance.statusForbiddenError': 'You do not have access to perform this action.',
  'attendance.serverError': 'Something went wrong while recording attendance. Please try again.',
  'attendance.connectionError': "We couldn't connect right now. Please check your internet and try again.",
  'requests.title': 'Leave Requests',
  'requests.yourBalance': 'YOUR BALANCE',
  'requests.requestHistory': 'REQUEST HISTORY',
  'requests.noHistory': 'No request history found.',
  'requests.requestLeave': 'Request Leave',
  'requests.leaveType': 'Leave Type',
  'requests.selectType': 'Select Type',
  'requests.startDate': 'Start Date',
  'requests.endDate': 'End Date',
  'requests.medicalReportRequired': 'Medical Report ID (Required)',
  'requests.enterDocumentId': 'Enter document ID...',
  'requests.noteOptional': 'Note (Optional)',
  'requests.addNote': 'Add a note...',
  'requests.submitRequest': 'Submit Request',
  'requests.cancelRequest': 'Cancel Request',
  'requests.readMore': 'Read more',
  'requests.requestDetails': 'Request details',
  'requests.reason': 'Reason',
  'requests.noteFromApprover': 'Note from approver',
  'requests.dateRange': 'Date range',
  'requests.status': 'Status',
  'requests.requestedDays': 'Requested days',
  'requests.createdAt': 'Created',
  'requests.reviewedAt': 'Reviewed',
  'requests.validationTitle': 'Check your dates',
  'requests.datesRequiredError': 'Start date and end date are required.',
  'requests.startDatePastError': 'Start date cannot be before today.',
  'requests.endDateBeforeStartError': 'End date cannot be before start date.',
  'requests.submitRequestError': 'Failed to submit leave request. Please try again.',
  'requests.cancelSuccessTitle': 'Request cancelled',
  'requests.cancelSuccessMessage': 'Your leave request was cancelled successfully.',
  'requests.cancelRequestError': 'Failed to cancel leave request. Please try again.',
  'requests.cancelPayrollLockedError': 'This leave cannot be cancelled because payroll for this period has already been processed.',
  'requests.cancelAlreadyStartedError': 'This leave cannot be cancelled because it has already started.',
  'requests.availableDays': 'Available days',
  'requests.vacation': 'Vacation',
  'requests.sickLeave': 'Sick Leave',
  'requests.personal': 'Personal Leave',
  'requests.unpaid': 'Unpaid Leave',
  'requests.parental': 'Parental Leave',
  'requests.other': 'Other Leave',
  'requests.companyPaidDays': 'Company paid',
  'requests.extraDays': 'extra (payroll deducted)',
  'requests.socialSecurityNote': 'days covered by social security',
  'requests.approved': 'Approved',
  'requests.pending': 'Pending',
  'requests.rejected': 'Rejected',
  'requests.cancelled': 'Cancelled',
  'payroll.title': 'Payroll',
  'payroll.notIncluded': 'Payroll not included',
  'payroll.upgradeText': 'Payroll is available on Growth and Professional plans. Upgrade at worknest.com.',
  'payroll.current': 'Current',
  'payroll.netPay': 'Net pay',
  'payroll.sessionRequiredTitle': 'Session required',
  'payroll.sessionRequiredMessage': 'Please sign in again before downloading your payslip.',
  'payroll.downloadFailedTitle': 'Download failed',
  'payroll.downloadFailedMessage': 'Unable to download payslip.',
  'payroll.downloadFailedPeriodMessage': 'Unable to download the payslip for this period.',
  'payroll.downloadUnavailableMessage': 'The payslip could not be downloaded right now.',
  'payroll.openPdfTitle': 'Open Payslip PDF',
  'payroll.savedTitle': 'Saved',
  'payroll.savedMessage': 'Payslip saved to device cache.',
  'payroll.detailsLoadError': 'Unable to load payroll details for this period.',
  'payroll.previewWarning': 'Live preview - figures may change until payroll is locked',
  'payroll.locked': 'Locked',
  'payroll.method': 'Method',
  'payroll.calculation': 'Calculation',
  'payroll.currency': 'Currency',
  'payroll.warnings': 'Warnings',
  'payroll.totals': 'Totals',
  'payroll.basePay': 'Base pay',
  'payroll.overtimePay': 'Overtime pay',
  'payroll.grossEarnings': 'Gross earnings',
  'payroll.statutoryDeductions': 'Statutory deductions',
  'payroll.totalDeductions': 'Total deductions',
  'payroll.employerCost': 'Employer cost',
  'payroll.netPayNegativeWarning': 'Net pay is negative - deductions exceed earnings for this period.',
  'payroll.socialSecurityBase': 'Social security base',
  'payroll.pensionBase': 'Pension base',
  'payroll.taxableIncome': 'Taxable income',
  'payroll.employeeSocialSecurity': 'Employee social security',
  'payroll.employeePension': 'Employee pension',
  'payroll.incomeTax': 'Income tax',
  'payroll.totalDeducted': 'Total deducted',
  'payroll.employerSocialSecurity': 'Employer social security',
  'payroll.employerPension': 'Employer pension',
  'payroll.employerCostTotal': 'Employer cost total',
  'payroll.systemDefaultRatesWarning': 'System default rates were used - no custom rates configured.',
  'payroll.taxBracketBreakdown': 'Tax bracket breakdown',
  'payroll.above': 'above',
  'payroll.rate': 'Rate',
  'payroll.taxableSlice': 'Taxable slice',
  'payroll.tax': 'Tax',
  'payroll.adjustments': 'Adjustments',
  'payroll.totalBonuses': 'Total bonuses',
  'payroll.totalManualDeductions': 'Total manual deductions',
  'payroll.bonuses': 'Bonuses',
  'payroll.manualDeductions': 'Manual deductions',
  'payroll.employmentPeriod': 'Employment period',
  'payroll.startDate': 'Start date',
  'payroll.endDate': 'End date',
  'payroll.payableFrom': 'Payable from',
  'payroll.payableTo': 'Payable to',
  'payroll.workPeriod': 'Work period',
  'payroll.calendarDays': 'Calendar days',
  'payroll.workingDays': 'Working days',
  'payroll.payableWorkingDays': 'Payable working days',
  'payroll.effectivePayableDays': 'Effective payable days',
  'payroll.dailyWorkingHours': 'Daily working hours',
  'payroll.payableHours': 'Payable hours',
  'payroll.hoursSource': 'Hours source',
  'payroll.effectiveAttendanceTo': 'Effective attendance to',
  'payroll.basePayCalculation': 'Base pay calculation',
  'payroll.formula': 'Formula',
  'payroll.monthlySalary': 'Monthly salary',
  'payroll.hourlyRate': 'Hourly rate',
  'payroll.workingDaysInMonth': 'Working days in month',
  'payroll.prorationMethod': 'Proration method',
  'payroll.overtime': 'Overtime',
  'payroll.expectedHours': 'Expected hours',
  'payroll.workedHours': 'Worked hours',
  'payroll.overtimeHours': 'Overtime hours',
  'payroll.overtimeRate': 'Overtime rate',
  'payroll.hourlyAttendance': 'Hourly attendance',
  'payroll.fullPayableHours': 'Full payable hours',
  'payroll.attendedHours': 'Attended hours',
  'payroll.fullPayment': 'Full payment',
  'payroll.attendanceDeduction': 'Attendance deduction',
  'payroll.paymentReceived': 'Payment received',
  'payroll.leaveCalculation': 'Leave calculation',
  'payroll.annualAllowanceDays': 'Annual allowance (days)',
  'payroll.usedBeforeThisMonth': 'Used before this month',
  'payroll.takenThisMonth': 'Taken this month',
  'payroll.paidLeaveDays': 'Paid leave days',
  'payroll.paidLeaveAmount': 'Paid leave amount',
  'payroll.unpaidLeaveDays': 'Unpaid leave days',
  'payroll.unpaidLeaveDeduction': 'Unpaid leave deduction',
  'payroll.leaveRecordsIncluded': 'Leave records included',
  'payroll.daysCounted': 'Days counted',
  'payroll.treatment': 'Treatment',
  'payroll.sickLeave': 'Sick leave',
  'payroll.status': 'Status',
  'payroll.daysTaken': 'Days taken',
  'payroll.companyPaidDays': 'Company paid days',
  'payroll.unpaidSickLeaveDays': 'Unpaid sick leave days',
  'payroll.companyPaidPercent': 'Company paid %',
  'payroll.companyPaidAmount': 'Company paid amount',
  'payroll.paidDeductionEquivalent': 'Paid deduction equivalent',
  'payroll.totalDeduction': 'Total deduction',
  'payroll.paidSickLeaveHours': 'Paid sick leave hours',
  'payroll.unpaidSickLeaveHours': 'Unpaid sick leave hours',
  'payroll.unpaidSickLeaveAmount': 'Unpaid sick leave amount',
  'payroll.insuranceCoveredDays': 'Insurance covered days',
  'payroll.insuranceCoveredAmount': 'Insurance covered amount',
  'payroll.absenceDetails': 'Absence details',
  'payroll.informationalOnly': 'Informational only.',
  'payroll.deductionApplied': 'Deduction applied.',
  'payroll.noDeductionApplied': 'No deduction applied.',
  'payroll.expectedWorkingMinutes': 'Expected working minutes',
  'payroll.attendedMinutes': 'Attended minutes',
  'payroll.absentMinutes': 'Absent minutes',
  'payroll.monetaryEquivalent': 'Monetary equivalent',
  'payroll.applied': 'Applied',
  'payroll.cardHint': 'Tap to view your payroll breakdown and download the payslip PDF.',
  'payroll.details': 'Payroll Details',
  'payroll.loadingDetails': 'Loading payroll details...',
  'payroll.downloadPdf': 'Download payslip PDF',
  'payroll.downloading': 'Downloading...',
  'payroll.pdfUnavailable': 'PDF not available - payroll must be calculated before downloading.',
  'updates.title': 'Announcements',
  'updates.noAnnouncements': 'No announcements yet',
  'updates.announcement': 'Announcement',
  'updates.important': 'Important',
  'updates.general': 'General',
  'updates.markAsRead': 'Mark as read',
  'updates.justNow': 'just now',
  'updates.yesterday': 'yesterday',
  'updates.minutesAgo': 'm ago',
  'updates.hoursAgo': 'h ago',
  'updates.daysAgo': 'days ago',
  'updates.monthAgo': 'month ago',
  'updates.monthsAgo': 'months ago',
  'profile.employmentInformation': 'Employment Information',
  'profile.department': 'Department',
  'profile.site': 'Site',
  'profile.contract': 'Contract',
  'profile.contractType': 'Contract Type',
  'profile.contractStatus': 'Contract Status',
  'profile.contractStartDate': 'Contract Start Date',
  'profile.contractEndDate': 'Contract End Date',
  'profile.language': 'Language',
  'profile.selectLanguage': 'Select Language',
  'profile.currentLanguage': 'Current language',
  'profile.changePassword': 'Change Password',
  'profile.changePasswordSubtitle': 'Update your password',
  'profile.currentPassword': 'Current Password',
  'profile.newPassword': 'New Password',
  'profile.confirmNewPassword': 'Confirm New Password',
  'profile.passwordRules': 'Password rules',
  'profile.changePasswordSuccess': 'Password changed successfully!',
  'profile.changePasswordSuccessSubtitle': 'Your password has been successfully updated.',
  'profile.updatingPassword': 'Updating password...',
  'profile.differentPasswordError': 'New password must be different from current password.',
  'profile.passwordsMustMatch': 'New password and confirm password must match.',
  'profile.allFieldsRequired': 'All fields are required.',
  'profile.logout': 'Log Out',
  'employees.title': 'Employees',
  'employees.subtitle': 'Manage your workforce here.',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.welcomeBack': 'Welcome Back',
  'auth.signInToContinue': 'Sign in to continue',
  'auth.forgotPassword': 'Forgot password?',
  'auth.login': 'Login',
  'auth.loggingIn': 'Logging in...',
  'auth.backToLogin': 'Back to Login',
  'auth.emailAddress': 'Email Address',
  'auth.emailPlaceholder': 'your.email@company.com',
  'auth.emailRequiredError': '* Please enter your email address',
  'auth.forgotPasswordTitle': 'Reset your password',
  'auth.forgotPasswordSubtitle': 'We will send a reset link to your email',
  'auth.sendResetLink': 'Send Reset Link',
  'auth.sending': 'Sending...',
  'auth.resetInstructionsSent': 'If the account exists, reset instructions will be sent.',
  'auth.resetEmailFallbackError': 'Unable to send reset email right now. Please try again.',
  'auth.emailSentTitle': 'Email Sent Successfully!',
  'auth.emailSentSubtitle': 'We have sent you a password reset link. Please check your email and follow the instructions to continue.',
  'auth.resetPasswordTitle': 'Reset Password',
  'auth.resetPasswordSubtitle': 'Set your new password and sign in again.',
  'auth.resetToken': 'Reset token',
  'auth.resetTokenRequired': 'Reset token is required.',
  'auth.newPassword': 'New password',
  'auth.confirmPassword': 'Confirm password',
  'auth.enterNewPassword': 'Enter new password',
  'auth.confirmNewPassword': 'Confirm new password',
  'auth.passwordInvalid': 'Password is invalid.',
  'auth.passwordMinLengthError': 'Password must be at least 8 characters long.',
  'auth.passwordUppercaseError': 'Password must include at least one uppercase letter.',
  'auth.passwordDigitError': 'Password must include at least one digit.',
  'auth.passwordEmailError': 'Password must not be the same as your email.',
  'auth.passwordMismatchError': 'Passwords do not match.',
  'auth.passwordRuleTitle': 'Password must:',
  'auth.passwordRuleMinLength': 'Be at least 8 characters long',
  'auth.passwordRuleUppercaseDigit': 'Include 1 uppercase and 1 digit',
  'auth.passwordRuleMatch': 'Match in both fields',
  'auth.resetting': 'Resetting...',
  'auth.resetSuccessMessage': 'Password reset successfully. Please login with your new password.',
  'auth.requestNewLink': 'Request new link',
  'auth.createNewPasswordTitle': 'Create New Password',
  'auth.createNewPasswordSubtitle': 'Enter your new password below',
  'auth.updatePassword': 'Update Password',
  'auth.passwordUpdatedTitle': 'Password Updated!',
  'auth.passwordUpdatedSubtitle': 'Your password has been successfully updated. You can now log in with your new password.',
  'auth.linkExpiredTitle': 'Link Expired!',
  'auth.linkExpiredSubtitle': 'This password reset link has expired. Please request a new one to continue.',
  'auth.sessionExpiredTitle': 'Session Expired!',
  'auth.sessionExpiredSubtitle': 'Your session has expired due to inactivity. Please log in again to continue using your account.',
  'auth.redirectingToLogin': 'Redirecting to login...',
  'auth.chooseWorkspace': 'Choose Workspace',
  'auth.chooseWorkspaceSubtitle': 'Select the role assignment you want to use in WorkNest Mobile.',
  'auth.noRoleAssignments': 'No role assignments available. Please contact your administrator.',
  'auth.select': 'Select',
  'auth.invitationTokenTitle': 'Invitation Token',
  'auth.invitationToken': 'Invitation token',
  'auth.invitationTokenRequired': 'Invitation token is required.',
  'auth.invitationPreflightSubtitle': 'Validate your invitation before activating your account.',
  'auth.validating': 'Validating...',
  'auth.validateInvitation': 'Validate Invitation',
  'auth.tryAnotherToken': 'Try another token',
  'auth.continueToActivation': 'Continue to Activation',
  'auth.activateInvitationTitle': 'Activate Invitation',
  'auth.activateInvitationSubtitle': 'Set a password, provide consent, and finish account activation.',
  'auth.invitationTokenMissing': 'Invitation token is missing.',
  'auth.gdprConsentRequired': 'GDPR consent is required.',
  'auth.preferredLanguageOptional': 'Preferred language (optional)',
  'auth.gdprConsent': 'I consent to GDPR data processing.',
  'auth.activating': 'Activating...',
  'auth.activateInvitation': 'Activate Invitation',
  'auth.invitationActivatedTitle': 'Invitation activated',
  'auth.invitationActivatedMessage': 'Your account is ready. Please login to continue.',
  'auth.error.invalidCredentials': 'Invalid email or password',
  'auth.error.accountLocked': 'Account temporarily locked. Try again later',
  'auth.error.noPlatformAccess': 'This account has no mobile access',
  'auth.error.userPending': 'Your account is pending activation',
  'auth.error.userSuspended': 'Your account is suspended',
  'auth.error.userDeactivated': 'Your account is deactivated',
  'auth.error.roleAssignmentNotFound': 'Selected role assignment is not valid anymore',
  'auth.error.roleAssignmentInactive': 'Selected role assignment is inactive',
  'auth.error.roleAssignmentForbidden': 'You cannot access this role assignment',
  'auth.error.sessionExpired': 'Your session has expired. Please sign in again',
  'auth.error.accessDenied': 'You are not authorized for this action.',
  'auth.error.resetTokenInvalid': 'This reset link is invalid. Request a new password reset link.',
  'auth.error.resetTokenExpired': 'This reset link has expired. Request a new password reset link.',
  'auth.error.resetTokenAlreadyUsed': 'This reset link was already used. Request a new password reset link.',
  'auth.error.invitationTokenInvalid': 'This invitation token is invalid. Please request a new invitation.',
  'auth.error.invitationTokenExpired': 'This invitation token has expired. Please request a new invitation.',
  'auth.error.invitationAlreadyUsed': 'This invitation has already been used. Please contact your administrator.',
  'auth.error.unknown': 'Something went wrong. Please try again.',
  'notifications.title': 'Notifications',
  'notifications.newBadge': 'new',
  'notifications.leaveApproved': 'Leave Request Approved',
  'notifications.payslipReady': 'Payslip Ready',
  'notifications.newAnnouncement': 'New Announcement',
  'notifications.leaveRejected': 'Leave Request Rejected',
  'notifications.leaveApprovedMessage': 'Your leave request has been approved.',
  'notifications.leaveRejectedMessage': 'Your leave request has been rejected.',
  'notifications.leaveRejectedReason': 'Reason',
  'notifications.empty': 'No notifications yet',
  'notifications.error': 'Failed to load notifications',
  'notifications.loading': 'Loading notifications...',
} as const;

export type TranslationKey = keyof typeof en;
type TranslationMap = Record<TranslationKey, string>;

const translations: Record<LanguageCode, TranslationMap> = {
  en,
  sq: {
    ...en,
    'nav.home': 'Kreu',
    'nav.attendance': 'Prezenca',
    'nav.requests': 'Kerkesat',
    'nav.payroll': 'Pagat',
    'nav.updates': 'Njoftimet',
    'nav.profile': 'Profili',
    'common.cancel': 'Anulo',
    'common.done': 'U krye',
    'common.current': 'Aktuale',
    'common.new': 'te reja',
    'common.notAvailable': 'N/A',
    'common.notAssigned': 'I pacaktuar',
    'common.day': 'dite',
    'common.days': 'dite',
    'common.tryAgain': 'Provo perseri',
    'common.loading': 'Duke ngarkuar...',
    'common.error': 'Gabim',
    'common.retry': 'Riprovo',
    'common.success': 'Sukses',
    'common.yes': 'Po',
    'common.no': 'Jo',
    'common.email': 'Email',
    'common.role': 'Roli',
    'common.jobTitle': 'Titulli i punes',
    'common.docs': 'Dokumentet',
    'home.hello': 'Pershendetje,',
    'home.attendance': 'Prezenca',
    'home.today': 'Sot',
    'home.checkedInAt': 'Hyrje ne',
    'home.notCheckedIn': 'Nuk ke bere hyrje',
    'home.leaveBalance': 'Bilanci i pushimeve',
    'home.noActiveLeaveBalances': 'Nuk ka bilance aktive',
    'home.latestPayroll': 'Paga e fundit',
    'home.noPayrollData': 'Nuk ka te dhena page',
    'home.announcements': 'Njoftime',
    'attendance.title': 'Prezenca',
    'attendance.clock': 'Regjistro',
    'attendance.clockIn': 'Regjistro hyrjen',
    'attendance.clockOut': 'Regjistro daljen',
    'attendance.actionBlocked': 'Veprim i bllokuar',
    'attendance.noActionAvailable': 'Nuk ka veprim',
    'attendance.loadingState': 'Duke ngarkuar gjendjen...',
    'attendance.blockedHint': 'Veprimi i prezences eshte i bllokuar.',
    'attendance.unavailableReason': 'Veprimi i prezences nuk eshte i disponueshem.',
    'attendance.clockInHint': 'Prek per te regjistruar hyrjen',
    'attendance.clockOutHint': 'Prek per te regjistruar daljen',
    'attendance.completedHint': 'Prezenca per sot ka perfunduar.',
    'attendance.submitting': 'Duke derguar prezencen...',
    'attendance.qrRequired': 'Kerkohet QR',
    'attendance.gpsRequired': 'Kerkohet GPS',
    'attendance.clockHint': 'Prek butonin me siper per te regjistruar prezencen.',
    'attendance.todayRecords': 'Regjistrimet e sotme',
    'attendance.dayStatus': 'Statusi i dites',
    'attendance.workedMinutes': 'Minuta pune',
    'attendance.present': 'Prezent',
    'attendance.absent': 'Mungon',
    'attendance.late': 'Me vonese',
    'attendance.halfDay': 'Gjysme dite',
    'attendance.leaveHoliday': 'Pushim/Feste',
    'attendance.noCheckout': 'Pa dalje',
    'attendance.pending': 'Ne pritje',
    'attendance.loadingCalendar': 'Duke ngarkuar kalendarin...',
    'attendance.status': 'Statusi',
    'attendance.scanSiteQr': 'Skano QR e vendit',
    'attendance.scanSiteQrHint': 'Drejto kameren te kodi QR i vendit.',
    'attendance.webQrUnavailable': 'Skanimi me kamere nuk eshte i disponueshem ne web. Vendos tokenin QR.',
    'attendance.pasteQrToken': 'Vendos tokenin QR',
    'attendance.useToken': 'Perdor tokenin',
    'attendance.preparingCamera': 'Duke pergatitur kameren...',
    'attendance.cameraPermission': 'Leja e kameres kerkohet per skanim.',
    'attendance.allowCamera': 'Lejo kameren',
    'attendance.alignQr': 'Vendos QR brenda kornizes',
    'attendance.loadingData': 'Duke ngarkuar te dhenat e prezences...',
    'attendance.refreshing': 'Duke rifreskuar...',
    'attendance.retrySync': 'Riprovo sinkronizimin',
    'attendance.locationUnavailableTitle': 'Lokacioni nuk eshte i disponueshem',
    'attendance.locationUnavailableMessage': 'Nuk mund te merrnim lokacionin ne kohe. Deshiron te provosh perseri?',
    'attendance.invalidQr': 'Kod QR i pavlefshem. Skano QR e duhur te vendit.',
    'attendance.qrValidationFailed': 'Verifikimi i QR deshtoi. Provo perseri.',
    'attendance.recordedWithWarnings': 'Prezenca u regjistrua me paralajmerime.',
    'attendance.recordedSuccessfully': 'Prezenca u regjistrua me sukses.',
    'attendance.locationRequiredError': 'Lokacioni kerkohet per te regjistruar prezencen ne kete vend.',
    'attendance.locationTimeoutError': 'Nuk mund te merrnim lokacionin ne kohe. Provo kur sinjali GPS eshte stabil.',
    'attendance.loadError': 'Nuk mund te ngarkonim prezencen. Provo perseri.',
    'requests.title': 'Kerkesa pushimi',
    'requests.yourBalance': 'BILANCI YT',
    'requests.requestHistory': 'HISTORIKU I KERKESAVE',
    'requests.noHistory': 'Nuk u gjet historik kerkesash.',
    'requests.requestLeave': 'Kerko pushim',
    'requests.leaveType': 'Lloji i pushimit',
    'requests.selectType': 'Zgjidh llojin',
    'requests.startDate': 'Data e fillimit',
    'requests.endDate': 'Data e perfundimit',
    'requests.medicalReportRequired': 'ID e raportit mjekesor (E detyrueshme)',
    'requests.enterDocumentId': 'Vendos ID dokumenti...',
    'requests.noteOptional': 'Shenim (Opsional)',
    'requests.addNote': 'Shto shenim...',
    'requests.submitRequest': 'Dergo kerkesen',
    'requests.cancelRequest': 'Anulo kerkesen',
    'requests.readMore': 'Lexo me shume',
    'requests.requestDetails': 'Detajet e kerkeses',
    'requests.reason': 'Arsyeja',
    'requests.noteFromApprover': 'Shenim nga aprovuesi',
    'requests.dateRange': 'Periudha',
    'requests.status': 'Statusi',
    'requests.requestedDays': 'Ditet e kerkuara',
    'requests.createdAt': 'Krijuar',
    'requests.reviewedAt': 'Shqyrtuar',
    'requests.validationTitle': 'Kontrollo datat',
    'requests.datesRequiredError': 'Data e fillimit dhe data e perfundimit jane te detyrueshme.',
    'requests.startDatePastError': 'Data e fillimit nuk mund te jete para dites se sotme.',
    'requests.endDateBeforeStartError': 'Data e perfundimit nuk mund te jete para dates se fillimit.',
    'requests.submitRequestError': 'Kerkesa per pushim nuk u dergua. Ju lutemi provoni perseri.',
    'requests.cancelSuccessTitle': 'Kerkesa u anulua',
    'requests.cancelSuccessMessage': 'Kerkesa juaj per pushim u anulua me sukses.',
    'requests.cancelRequestError': 'Kerkesa per pushim nuk u anulua. Ju lutemi provoni perseri.',
    'requests.cancelPayrollLockedError': 'Ky pushim nuk mund te anulohet sepse paga per kete periudhe eshte procesuar.',
    'requests.cancelAlreadyStartedError': 'Ky pushim nuk mund te anulohet sepse ka filluar tashme.',
    'requests.availableDays': 'Dite te disponueshme',
    'requests.vacation': 'Pushim',
    'requests.sickLeave': 'Raport mjekesor',
    'requests.personal': 'Leje personale',
    'requests.unpaid': 'Leje pa pagese',
    'requests.parental': 'Leje prinderore',
    'requests.other': 'Leje tjeter',
    'requests.companyPaidDays': 'Paguar nga kompania',
    'requests.extraDays': 'ekstra (zbriten nga paga)',
    'requests.socialSecurityNote': 'dite te mbuluara nga sigurimet shoqerore',
    'requests.approved': 'Aprovuar',
    'requests.pending': 'Ne pritje',
    'requests.rejected': 'Refuzuar',
    'requests.cancelled': 'Anuluar',
    'payroll.title': 'Pagat',
    'payroll.notIncluded': 'Pagat nuk perfshihen',
    'payroll.upgradeText': 'Pagat jane te disponueshme ne planet Growth dhe Professional. Perditeso ne worknest.com.',
    'payroll.netPay': 'Paga neto',
    'payroll.cardHint': 'Prek per te pare detajet e pages dhe per te shkarkuar PDF.',
    'payroll.details': 'Detajet e pages',
    'payroll.loadingDetails': 'Duke ngarkuar detajet...',
    'payroll.downloadPdf': 'Shkarko PDF e pages',
    'payroll.downloading': 'Duke shkarkuar...',
    'payroll.pdfUnavailable': 'PDF nuk eshte i disponueshem - paga duhet llogaritur para shkarkimit.',
    'updates.title': 'Njoftime',
    'updates.noAnnouncements': 'Nuk ka njoftime ende',
    'updates.announcement': 'Njoftim',
    'updates.important': 'E rendesishme',
    'updates.general': 'E pergjithshme',
    'updates.markAsRead': 'Sheno si lexuar',
    'updates.justNow': 'tani',
    'updates.yesterday': 'dje',
    'updates.minutesAgo': 'min me pare',
    'updates.hoursAgo': 'ore me pare',
    'updates.daysAgo': 'dite me pare',
    'updates.monthAgo': 'muaj me pare',
    'updates.monthsAgo': 'muaj me pare',
    'profile.employmentInformation': 'Informacioni i punesimit',
    'profile.department': 'Departamenti',
    'profile.site': 'Lokacioni',
    'profile.contract': 'Kontrata',
    'profile.contractType': 'Lloji i kontrates',
    'profile.contractStatus': 'Statusi i kontrates',
    'profile.contractStartDate': 'Data e fillimit te kontrates',
    'profile.contractEndDate': 'Data e perfundimit te kontrates',
    'profile.language': 'Gjuha',
    'profile.selectLanguage': 'Zgjidh gjuhen',
    'profile.currentLanguage': 'Gjuha aktuale',
    'profile.changePassword': 'Ndrysho fjalekalimin',
    'profile.changePasswordSubtitle': 'Perditeso fjalekalimin',
    'profile.currentPassword': 'Fjalekalimi Aktual',
    'profile.newPassword': 'Fjalekalimi i Ri',
    'profile.confirmNewPassword': 'Konfirmo Fjalekalimin e Ri',
    'profile.passwordRules': 'Rregullat e fjalekalimit',
    'profile.changePasswordSuccess': 'Fjalekalimi u ndryshua me sukses!',
    'profile.changePasswordSuccessSubtitle': 'Fjalekalimi juaj u përditësua me sukses.',
    'profile.updatingPassword': 'Duke përditësuar fjalekalimin...',
    'profile.differentPasswordError': 'Fjalekalimi i ri duhet të jetë i ndryshëm nga ai aktual.',
    'profile.passwordsMustMatch': 'Fjalekalimi i ri dhe konfirmimi duhet të përputhen.',
    'profile.allFieldsRequired': 'Të gjitha fushat janë të detyrueshme.',
    'profile.logout': 'Dil',
    'employees.title': 'Punonjesit',
    'employees.subtitle': 'Menaxho ekipin ketu.',
    'auth.email': 'Email',
    'auth.password': 'Fjalekalimi',
    'auth.welcomeBack': 'Mire se u ktheve',
    'auth.signInToContinue': 'Hyr per te vazhduar',
    'auth.forgotPassword': 'Harruat fjalekalimin?',
    'auth.login': 'Hyr',
    'auth.loggingIn': 'Duke hyre...',
    'auth.backToLogin': 'Kthehu te hyrja',
    'auth.emailAddress': 'Adresa e emailit',
    'auth.emailPlaceholder': 'emaili.juaj@kompania.com',
    'auth.emailRequiredError': '* Ju lutemi vendosni adresen e emailit',
    'auth.forgotPasswordTitle': 'Rivendos fjalekalimin',
    'auth.forgotPasswordSubtitle': 'Do te dergojme nje link rivendosjeje ne emailin tuaj',
    'auth.sendResetLink': 'Dergo linkun',
    'auth.sending': 'Duke derguar...',
    'auth.resetInstructionsSent': 'Nese llogaria ekziston, udhezimet do te dergohen.',
    'auth.resetEmailFallbackError': 'Emaili i rivendosjes nuk mund te dergohet tani. Provo perseri.',
    'auth.emailSentTitle': 'Emaili u dergua me sukses!',
    'auth.emailSentSubtitle': 'Ju kemi derguar nje link per rivendosjen e fjalekalimit. Kontrolloni emailin dhe ndiqni udhezimet.',
    'auth.resetPasswordTitle': 'Rivendos fjalekalimin',
    'auth.resetPasswordSubtitle': 'Vendos fjalekalimin e ri dhe hy perseri.',
    'auth.resetToken': 'Token rivendosjeje',
    'auth.resetTokenRequired': 'Tokeni i rivendosjes eshte i detyrueshem.',
    'auth.newPassword': 'Fjalekalim i ri',
    'auth.confirmPassword': 'Konfirmo fjalekalimin',
    'auth.enterNewPassword': 'Vendos fjalekalimin e ri',
    'auth.confirmNewPassword': 'Konfirmo fjalekalimin e ri',
    'auth.passwordInvalid': 'Fjalekalimi nuk eshte i vlefshem.',
    'auth.passwordMinLengthError': 'Fjalekalimi duhet te kete te pakten 8 karaktere.',
    'auth.passwordUppercaseError': 'Fjalekalimi duhet te kete te pakten nje shkronje te madhe.',
    'auth.passwordDigitError': 'Fjalekalimi duhet te kete te pakten nje numer.',
    'auth.passwordEmailError': 'Fjalekalimi nuk duhet te jete i njejte me emailin.',
    'auth.passwordMismatchError': 'Fjalekalimet nuk perputhen.',
    'auth.passwordRuleTitle': 'Fjalekalimi duhet:',
    'auth.passwordRuleMinLength': 'Te kete te pakten 8 karaktere',
    'auth.passwordRuleUppercaseDigit': 'Te perfshije 1 shkronje te madhe dhe 1 numer',
    'auth.passwordRuleMatch': 'Te perputhet ne te dyja fushat',
    'auth.resetting': 'Duke rivendosur...',
    'auth.resetSuccessMessage': 'Fjalekalimi u rivendos me sukses. Ju lutemi hyni me fjalekalimin e ri.',
    'auth.requestNewLink': 'Kerko link te ri',
    'auth.createNewPasswordTitle': 'Krijo fjalekalim te ri',
    'auth.createNewPasswordSubtitle': 'Vendos fjalekalimin e ri me poshte',
    'auth.updatePassword': 'Perditeso fjalekalimin',
    'auth.passwordUpdatedTitle': 'Fjalekalimi u perditesua!',
    'auth.passwordUpdatedSubtitle': 'Fjalekalimi juaj u perditesua me sukses. Tani mund te hyni me fjalekalimin e ri.',
    'auth.linkExpiredTitle': 'Linku ka skaduar!',
    'auth.linkExpiredSubtitle': 'Ky link per rivendosjen e fjalekalimit ka skaduar. Kerko nje te ri per te vazhduar.',
    'auth.sessionExpiredTitle': 'Seanca ka skaduar!',
    'auth.sessionExpiredSubtitle': 'Seanca juaj ka skaduar nga pasiviteti. Ju lutemi hyni perseri per te vazhduar.',
    'auth.redirectingToLogin': 'Duke u kthyer te hyrja...',
    'auth.chooseWorkspace': 'Zgjidh hapesiren e punes',
    'auth.chooseWorkspaceSubtitle': 'Zgjidh rolin qe deshiron te perdoresh ne WorkNest Mobile.',
    'auth.noRoleAssignments': 'Nuk ka role te disponueshme. Kontakto administratorin.',
    'auth.select': 'Zgjidh',
    'auth.invitationTokenTitle': 'Tokeni i fteses',
    'auth.invitationToken': 'Token ftese',
    'auth.invitationTokenRequired': 'Tokeni i fteses eshte i detyrueshem.',
    'auth.invitationPreflightSubtitle': 'Verifiko ftesen para aktivizimit te llogarise.',
    'auth.validating': 'Duke verifikuar...',
    'auth.validateInvitation': 'Verifiko ftesen',
    'auth.tryAnotherToken': 'Provo token tjeter',
    'auth.continueToActivation': 'Vazhdo te aktivizimi',
    'auth.activateInvitationTitle': 'Aktivizo ftesen',
    'auth.activateInvitationSubtitle': 'Vendos fjalekalimin, jep pelqimin dhe perfundo aktivizimin.',
    'auth.invitationTokenMissing': 'Tokeni i fteses mungon.',
    'auth.gdprConsentRequired': 'Pelqimi GDPR eshte i detyrueshem.',
    'auth.preferredLanguageOptional': 'Gjuha e preferuar (opsionale)',
    'auth.gdprConsent': 'Pranoj perpunimin e te dhenave sipas GDPR.',
    'auth.activating': 'Duke aktivizuar...',
    'auth.activateInvitation': 'Aktivizo ftesen',
    'auth.invitationActivatedTitle': 'Ftesa u aktivizua',
    'auth.invitationActivatedMessage': 'Llogaria juaj eshte gati. Ju lutemi hyni per te vazhduar.',
    'auth.error.invalidCredentials': 'Email ose fjalekalim i pavlefshem',
    'auth.error.accountLocked': 'Llogaria eshte bllokuar perkohesisht. Provo me vone',
    'auth.error.noPlatformAccess': 'Kjo llogari nuk ka akses ne mobile',
    'auth.error.userPending': 'Llogaria juaj pret aktivizim',
    'auth.error.userSuspended': 'Llogaria juaj eshte pezulluar',
    'auth.error.userDeactivated': 'Llogaria juaj eshte caktivizuar',
    'auth.error.roleAssignmentNotFound': 'Roli i zgjedhur nuk eshte me i vlefshem',
    'auth.error.roleAssignmentInactive': 'Roli i zgjedhur eshte joaktiv',
    'auth.error.roleAssignmentForbidden': 'Nuk mund te hysh ne kete rol',
    'auth.error.sessionExpired': 'Seanca juaj ka skaduar. Ju lutemi hyni perseri',
    'auth.error.accessDenied': 'Nuk je i autorizuar per kete veprim.',
    'auth.error.resetTokenInvalid': 'Ky link rivendosjeje nuk eshte i vlefshem. Kerko nje link te ri.',
    'auth.error.resetTokenExpired': 'Ky link rivendosjeje ka skaduar. Kerko nje link te ri.',
    'auth.error.resetTokenAlreadyUsed': 'Ky link rivendosjeje eshte perdorur. Kerko nje link te ri.',
    'auth.error.invitationTokenInvalid': 'Ky token ftese nuk eshte i vlefshem. Kerko nje ftese te re.',
    'auth.error.invitationTokenExpired': 'Ky token ftese ka skaduar. Kerko nje ftese te re.',
    'auth.error.invitationAlreadyUsed': 'Kjo ftese eshte perdorur. Kontakto administratorin.',
    'auth.error.unknown': 'Dicka shkoi keq. Ju lutemi provoni perseri.',
    'notifications.title': 'Njoftimet',
    'notifications.newBadge': 'të reja',
    'notifications.leaveApproved': 'Kërkesa për Pushim u Aprovua',
    'notifications.payslipReady': 'Paga është Gati',
    'notifications.newAnnouncement': 'Njoftim i Ri',
    'notifications.leaveRejected': 'Kërkesa për Pushim u Refuzuar',
    'notifications.leaveApprovedMessage': 'Kerkesa juaj per pushim u aprovua.',
    'notifications.leaveRejectedMessage': 'Kerkesa juaj per pushim u refuzua.',
    'notifications.leaveRejectedReason': 'Arsyeja',
    'notifications.empty': 'Nuk ka njoftime ende',
    'notifications.error': 'Dështoi ngarkimi i njoftimeve',
    'notifications.loading': 'Duke ngarkuar njoftimet...',
  },
  it: {
    ...en,
    'nav.home': 'Home',
    'nav.attendance': 'Presenze',
    'nav.requests': 'Richieste',
    'nav.payroll': 'Paghe',
    'nav.updates': 'Aggiornamenti',
    'nav.profile': 'Profilo',
    'common.cancel': 'Annulla',
    'common.done': 'Fatto',
    'common.current': 'Corrente',
    'common.new': 'nuovi',
    'common.notAssigned': 'Non assegnato',
    'common.notAvailable': 'N/D',
    'common.day': 'giorno',
    'common.days': 'giorni',
    'common.tryAgain': 'Riprova',
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.retry': 'Riprova',
    'common.success': 'Successo',
    'common.yes': 'Si',
    'common.no': 'No',
    'common.email': 'Email',
    'common.role': 'Ruolo',
    'common.jobTitle': 'Titolo lavoro',
    'common.docs': 'Documenti',
    'home.hello': 'Ciao,',
    'home.attendance': 'Presenze',
    'home.today': 'Oggi',
    'home.checkedInAt': 'Entrata alle',
    'home.notCheckedIn': 'Non entrato',
    'home.leaveBalance': 'Saldo ferie',
    'home.noActiveLeaveBalances': 'Nessun saldo ferie attivo',
    'home.latestPayroll': 'Ultima busta paga',
    'home.noPayrollData': 'Nessun dato paghe disponibile',
    'home.announcements': 'Annunci',
    'attendance.title': 'Presenze',
    'attendance.clock': 'Timbratura',
    'attendance.clockIn': 'Entrata',
    'attendance.clockOut': 'Uscita',
    'attendance.actionBlocked': 'Azione bloccata',
    'attendance.noActionAvailable': 'Nessuna azione',
    'attendance.loadingState': 'Caricamento stato presenze...',
    'attendance.blockedHint': 'Azione presenze bloccata.',
    'attendance.unavailableReason': 'Azione presenze non disponibile.',
    'attendance.clockInHint': 'Tocca per registrare entrata',
    'attendance.clockOutHint': 'Tocca per registrare uscita',
    'attendance.completedHint': 'Presenza gia completata per oggi.',
    'attendance.submitting': 'Invio presenza...',
    'attendance.qrRequired': 'QR richiesto',
    'attendance.gpsRequired': 'GPS richiesto',
    'attendance.clockHint': 'Tocca il pulsante sopra per registrare entrata o uscita.',
    'attendance.todayRecords': 'Registri di oggi',
    'attendance.dayStatus': 'Stato giorno',
    'attendance.workedMinutes': 'Minuti lavorati',
    'attendance.present': 'Presente',
    'attendance.absent': 'Assente',
    'attendance.late': 'In ritardo',
    'attendance.halfDay': 'Mezza giornata',
    'attendance.leaveHoliday': 'Ferie/Festivo',
    'attendance.noCheckout': 'Senza uscita',
    'attendance.pending': 'In attesa',
    'attendance.loadingCalendar': 'Caricamento calendario...',
    'attendance.status': 'Stato',
    'attendance.scanSiteQr': 'Scansiona QR sede',
    'attendance.scanSiteQrHint': 'Punta la fotocamera sul codice QR della sede.',
    'attendance.webQrUnavailable': 'La scansione camera non e disponibile sul web. Incolla il token QR.',
    'attendance.pasteQrToken': 'Incolla token QR',
    'attendance.useToken': 'Usa token',
    'attendance.preparingCamera': 'Preparazione camera...',
    'attendance.cameraPermission': 'Serve il permesso camera per scansionare il QR.',
    'attendance.allowCamera': 'Consenti camera',
    'attendance.alignQr': 'Allinea il QR dentro il riquadro',
    'attendance.loadingData': 'Caricamento dati presenze...',
    'attendance.refreshing': 'Aggiornamento...',
    'attendance.retrySync': 'Riprova sincronizzazione',
    'attendance.locationUnavailableTitle': 'Posizione non disponibile',
    'attendance.locationUnavailableMessage': 'Non siamo riusciti a ottenere la posizione in tempo. Vuoi riprovare?',
    'attendance.invalidQr': 'Codice QR non valido. Scansiona il QR corretto della sede.',
    'attendance.qrValidationFailed': 'Validazione QR non riuscita. Riprova.',
    'attendance.recordedWithWarnings': 'Presenza registrata con avvisi.',
    'attendance.recordedSuccessfully': 'Presenza registrata con successo.',
    'attendance.locationRequiredError': 'La posizione e richiesta per registrare la presenza in questa sede.',
    'attendance.locationTimeoutError': 'Non siamo riusciti a ottenere la posizione in tempo. Riprova quando il GPS e stabile.',
    'attendance.loadError': 'Non siamo riusciti a caricare le presenze. Riprova.',
    'requests.title': 'Richieste ferie',
    'requests.yourBalance': 'IL TUO SALDO',
    'requests.requestHistory': 'STORICO RICHIESTE',
    'requests.noHistory': 'Nessuno storico richieste trovato.',
    'requests.requestLeave': 'Richiedi ferie',
    'requests.leaveType': 'Tipo ferie',
    'requests.selectType': 'Seleziona tipo',
    'requests.startDate': 'Data inizio',
    'requests.endDate': 'Data fine',
    'requests.medicalReportRequired': 'ID certificato medico (Obbligatorio)',
    'requests.enterDocumentId': 'Inserisci ID documento...',
    'requests.noteOptional': 'Nota (Opzionale)',
    'requests.addNote': 'Aggiungi nota...',
    'requests.submitRequest': 'Invia richiesta',
    'requests.cancelRequest': 'Annulla richiesta',
    'requests.readMore': 'Leggi di più',
    'requests.requestDetails': 'Dettagli richiesta',
    'requests.reason': 'Motivo',
    'requests.noteFromApprover': 'Nota dell approvatore',
    'requests.dateRange': 'Periodo',
    'requests.status': 'Stato',
    'requests.requestedDays': 'Giorni richiesti',
    'requests.createdAt': 'Creata',
    'requests.reviewedAt': 'Revisionata',
    'requests.validationTitle': 'Controlla le date',
    'requests.datesRequiredError': 'Data inizio e data fine sono obbligatorie.',
    'requests.startDatePastError': 'La data inizio non può essere precedente a oggi.',
    'requests.endDateBeforeStartError': 'La data fine non può essere precedente alla data inizio.',
    'requests.submitRequestError': 'Impossibile inviare la richiesta ferie. Riprova.',
    'requests.cancelSuccessTitle': 'Richiesta annullata',
    'requests.cancelSuccessMessage': 'La richiesta ferie è stata annullata con successo.',
    'requests.cancelRequestError': 'Impossibile annullare la richiesta ferie. Riprova.',
    'requests.cancelPayrollLockedError': 'Questa ferie non può essere annullata perché il payroll per questo periodo è già stato elaborato.',
    'requests.cancelAlreadyStartedError': 'Questa ferie non può essere annullata perché è già iniziata.',
    'requests.availableDays': 'Giorni disponibili',
    'requests.vacation': 'Ferie',
    'requests.sickLeave': 'Malattia',
    'requests.personal': 'Permesso personale',
    'requests.unpaid': 'Permesso non retribuito',
    'requests.parental': 'Congedo parentale',
    'requests.other': 'Altro permesso',
    'requests.companyPaidDays': 'Pagato dall\'azienda',
    'requests.extraDays': 'extra (dedotti dalla busta paga)',
    'requests.socialSecurityNote': 'giorni coperti dalla previdenza sociale',
    'requests.approved': 'Approvata',
    'requests.pending': 'In attesa',
    'requests.rejected': 'Rifiutata',
    'requests.cancelled': 'Annullata',
    'payroll.title': 'Paghe',
    'payroll.notIncluded': 'Paghe non incluse',
    'payroll.upgradeText': 'Le paghe sono disponibili nei piani Growth e Professional. Aggiorna su worknest.com.',
    'payroll.current': 'Corrente',
    'payroll.netPay': 'Netto',
    'payroll.cardHint': 'Tocca per vedere il dettaglio paga e scaricare il PDF.',
    'payroll.details': 'Dettagli paga',
    'payroll.loadingDetails': 'Caricamento dettagli paga...',
    'payroll.downloadPdf': 'Scarica PDF busta paga',
    'payroll.downloading': 'Download...',
    'payroll.pdfUnavailable': 'PDF non disponibile - la paga deve essere calcolata prima del download.',
    'updates.title': 'Annunci',
    'updates.noAnnouncements': 'Nessun annuncio',
    'updates.announcement': 'Annuncio',
    'updates.important': 'Importante',
    'updates.general': 'Generale',
    'updates.markAsRead': 'Segna come letto',
    'updates.justNow': 'ora',
    'updates.yesterday': 'ieri',
    'updates.minutesAgo': 'min fa',
    'updates.hoursAgo': 'h fa',
    'updates.daysAgo': 'giorni fa',
    'updates.monthAgo': 'mese fa',
    'updates.monthsAgo': 'mesi fa',
    'profile.employmentInformation': 'Informazioni lavorative',
    'profile.department': 'Reparto',
    'profile.site': 'Sede',
    'profile.contract': 'Contratto',
    'profile.contractType': 'Tipo contratto',
    'profile.contractStatus': 'Stato contratto',
    'profile.contractStartDate': 'Data inizio contratto',
    'profile.contractEndDate': 'Data fine contratto',
    'profile.language': 'Lingua',
    'profile.selectLanguage': 'Seleziona lingua',
    'profile.currentLanguage': 'Lingua corrente',
    'profile.changePassword': 'Cambia password',
    'profile.changePasswordSubtitle': 'Aggiorna la password',
    'profile.currentPassword': 'Password Corrente',
    'profile.newPassword': 'Nuova Password',
    'profile.confirmNewPassword': 'Conferma Nuova Password',
    'profile.passwordRules': 'Regole password',
    'profile.changePasswordSuccess': 'Password cambiata con successo!',
    'profile.changePasswordSuccessSubtitle': 'La tua password è stata aggiornata con successo.',
    'profile.updatingPassword': 'Aggiornamento password...',
    'profile.differentPasswordError': 'La nuova password deve essere diversa da quella corrente.',
    'profile.passwordsMustMatch': 'La nuova password e la conferma devono coincidere.',
    'profile.allFieldsRequired': 'Tutti i campi sono obbligatori.',
    'profile.logout': 'Esci',
    'employees.title': 'Dipendenti',
    'employees.subtitle': 'Gestisci il personale qui.',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.welcomeBack': 'Bentornato',
    'auth.signInToContinue': 'Accedi per continuare',
    'auth.forgotPassword': 'Password dimenticata?',
    'auth.login': 'Accedi',
    'auth.loggingIn': 'Accesso...',
    'auth.backToLogin': 'Torna al login',
    'auth.emailAddress': 'Indirizzo email',
    'auth.emailPlaceholder': 'tua.email@azienda.com',
    'auth.emailRequiredError': '* Inserisci il tuo indirizzo email',
    'auth.forgotPasswordTitle': 'Reimposta la password',
    'auth.forgotPasswordSubtitle': 'Ti invieremo un link di reset via email',
    'auth.sendResetLink': 'Invia link di reset',
    'auth.sending': 'Invio...',
    'auth.resetInstructionsSent': 'Se l account esiste, riceverai le istruzioni.',
    'auth.resetEmailFallbackError': 'Impossibile inviare l email di reset ora. Riprova.',
    'auth.emailSentTitle': 'Email inviata con successo!',
    'auth.emailSentSubtitle': 'Ti abbiamo inviato un link per reimpostare la password. Controlla la tua email e segui le istruzioni.',
    'auth.resetPasswordTitle': 'Reimposta password',
    'auth.resetPasswordSubtitle': 'Imposta la nuova password e accedi di nuovo.',
    'auth.resetToken': 'Token di reset',
    'auth.resetTokenRequired': 'Il token di reset e obbligatorio.',
    'auth.newPassword': 'Nuova password',
    'auth.confirmPassword': 'Conferma password',
    'auth.enterNewPassword': 'Inserisci nuova password',
    'auth.confirmNewPassword': 'Conferma nuova password',
    'auth.passwordInvalid': 'La password non e valida.',
    'auth.passwordMinLengthError': 'La password deve avere almeno 8 caratteri.',
    'auth.passwordUppercaseError': 'La password deve includere almeno una lettera maiuscola.',
    'auth.passwordDigitError': 'La password deve includere almeno una cifra.',
    'auth.passwordEmailError': 'La password non deve essere uguale alla tua email.',
    'auth.passwordMismatchError': 'Le password non coincidono.',
    'auth.passwordRuleTitle': 'La password deve:',
    'auth.passwordRuleMinLength': 'Avere almeno 8 caratteri',
    'auth.passwordRuleUppercaseDigit': 'Includere 1 maiuscola e 1 cifra',
    'auth.passwordRuleMatch': 'Coincidere in entrambi i campi',
    'auth.resetting': 'Reimpostazione...',
    'auth.resetSuccessMessage': 'Password reimpostata con successo. Accedi con la nuova password.',
    'auth.requestNewLink': 'Richiedi nuovo link',
    'auth.createNewPasswordTitle': 'Crea nuova password',
    'auth.createNewPasswordSubtitle': 'Inserisci la nuova password qui sotto',
    'auth.updatePassword': 'Aggiorna password',
    'auth.passwordUpdatedTitle': 'Password aggiornata!',
    'auth.passwordUpdatedSubtitle': 'La tua password e stata aggiornata con successo. Ora puoi accedere con la nuova password.',
    'auth.linkExpiredTitle': 'Link scaduto!',
    'auth.linkExpiredSubtitle': 'Questo link di reset e scaduto. Richiedine uno nuovo per continuare.',
    'auth.sessionExpiredTitle': 'Sessione scaduta!',
    'auth.sessionExpiredSubtitle': 'La sessione e scaduta per inattivita. Accedi di nuovo per continuare.',
    'auth.redirectingToLogin': 'Reindirizzamento al login...',
    'auth.chooseWorkspace': 'Scegli workspace',
    'auth.chooseWorkspaceSubtitle': 'Seleziona il ruolo da usare in WorkNest Mobile.',
    'auth.noRoleAssignments': 'Nessun ruolo disponibile. Contatta l amministratore.',
    'auth.select': 'Seleziona',
    'auth.invitationTokenTitle': 'Token invito',
    'auth.invitationToken': 'Token invito',
    'auth.invitationTokenRequired': 'Il token invito e obbligatorio.',
    'auth.invitationPreflightSubtitle': 'Verifica l invito prima di attivare l account.',
    'auth.validating': 'Verifica...',
    'auth.validateInvitation': 'Verifica invito',
    'auth.tryAnotherToken': 'Prova un altro token',
    'auth.continueToActivation': 'Continua all attivazione',
    'auth.activateInvitationTitle': 'Attiva invito',
    'auth.activateInvitationSubtitle': 'Imposta una password, dai il consenso e completa l attivazione.',
    'auth.invitationTokenMissing': 'Token invito mancante.',
    'auth.gdprConsentRequired': 'Il consenso GDPR e obbligatorio.',
    'auth.preferredLanguageOptional': 'Lingua preferita (opzionale)',
    'auth.gdprConsent': 'Acconsento al trattamento dati GDPR.',
    'auth.activating': 'Attivazione...',
    'auth.activateInvitation': 'Attiva invito',
    'auth.invitationActivatedTitle': 'Invito attivato',
    'auth.invitationActivatedMessage': 'Il tuo account e pronto. Accedi per continuare.',
    'auth.error.invalidCredentials': 'Email o password non validi',
    'auth.error.accountLocked': 'Account temporaneamente bloccato. Riprova piu tardi',
    'auth.error.noPlatformAccess': 'Questo account non ha accesso mobile',
    'auth.error.userPending': 'Il tuo account e in attesa di attivazione',
    'auth.error.userSuspended': 'Il tuo account e sospeso',
    'auth.error.userDeactivated': 'Il tuo account e disattivato',
    'auth.error.roleAssignmentNotFound': 'Il ruolo selezionato non e piu valido',
    'auth.error.roleAssignmentInactive': 'Il ruolo selezionato non e attivo',
    'auth.error.roleAssignmentForbidden': 'Non puoi accedere a questo ruolo',
    'auth.error.sessionExpired': 'La sessione e scaduta. Accedi di nuovo',
    'auth.error.accessDenied': 'Non sei autorizzato per questa azione.',
    'auth.error.resetTokenInvalid': 'Questo link di reset non e valido. Richiedi un nuovo link.',
    'auth.error.resetTokenExpired': 'Questo link di reset e scaduto. Richiedi un nuovo link.',
    'auth.error.resetTokenAlreadyUsed': 'Questo link di reset e gia stato usato. Richiedi un nuovo link.',
    'auth.error.invitationTokenInvalid': 'Questo token invito non e valido. Richiedi un nuovo invito.',
    'auth.error.invitationTokenExpired': 'Questo token invito e scaduto. Richiedi un nuovo invito.',
    'auth.error.invitationAlreadyUsed': 'Questo invito e gia stato usato. Contatta l amministratore.',
    'auth.error.unknown': 'Qualcosa e andato storto. Riprova.',
    'notifications.title': 'Notifiche',
    'notifications.newBadge': 'nuovi',
    'notifications.leaveApproved': 'Richiesta Ferie Approvata',
    'notifications.payslipReady': 'Busta Paga Disponibile',
    'notifications.newAnnouncement': 'Nuovo Annuncio',
    'notifications.leaveRejected': 'Richiesta Ferie Rifiutata',
    'notifications.leaveApprovedMessage': 'La tua richiesta ferie e stata approvata.',
    'notifications.leaveRejectedMessage': 'La tua richiesta ferie e stata rifiutata.',
    'notifications.leaveRejectedReason': 'Motivo',
    'notifications.empty': 'Nessuna notifica ancora',
    'notifications.error': 'Impossibile caricare le notifiche',
    'notifications.loading': 'Caricamento notifiche...',
  },
  de: {
    ...en,
    'nav.home': 'Start',
    'nav.attendance': 'Anwesenheit',
    'nav.requests': 'Anfragen',
    'nav.payroll': 'Gehaltslauf',
    'nav.updates': 'Updates',
    'nav.profile': 'Profil',
    'common.cancel': 'Abbrechen',
    'common.done': 'Fertig',
    'common.current': 'Aktuell',
    'common.new': 'neu',
    'common.notAssigned': 'Nicht zugewiesen',
    'common.notAvailable': 'N/V',
    'common.day': 'Tag',
    'common.days': 'Tage',
    'common.tryAgain': 'Erneut versuchen',
    'common.loading': 'Wird geladen...',
    'common.error': 'Fehler',
    'common.retry': 'Erneut versuchen',
    'common.success': 'Erfolg',
    'common.yes': 'Ja',
    'common.no': 'Nein',
    'common.email': 'E-Mail',
    'common.role': 'Rolle',
    'common.jobTitle': 'Jobtitel',
    'common.docs': 'Dokumente',
    'home.hello': 'Hallo,',
    'home.attendance': 'Anwesenheit',
    'home.today': 'Heute',
    'home.checkedInAt': 'Eingecheckt um',
    'home.notCheckedIn': 'Nicht eingecheckt',
    'home.leaveBalance': 'Urlaubssaldo',
    'home.noActiveLeaveBalances': 'Keine aktiven Urlaubssalden',
    'home.latestPayroll': 'Letzte Abrechnung',
    'home.noPayrollData': 'Keine Gehaltsdaten verfugbar',
    'home.announcements': 'Ankundigungen',
    'attendance.title': 'Anwesenheit',
    'attendance.clock': 'Stempeln',
    'attendance.clockIn': 'Einstempeln',
    'attendance.clockOut': 'Ausstempeln',
    'attendance.actionBlocked': 'Aktion blockiert',
    'attendance.noActionAvailable': 'Keine Aktion verfugbar',
    'attendance.loadingState': 'Anwesenheitsstatus wird geladen...',
    'attendance.blockedHint': 'Anwesenheitsaktion ist blockiert.',
    'attendance.unavailableReason': 'Anwesenheitsaktion ist derzeit nicht verfugbar.',
    'attendance.clockInHint': 'Tippen zum Einstempeln',
    'attendance.clockOutHint': 'Tippen zum Ausstempeln',
    'attendance.completedHint': 'Anwesenheit ist heute bereits abgeschlossen.',
    'attendance.submitting': 'Anwesenheit wird gesendet...',
    'attendance.qrRequired': 'QR erforderlich',
    'attendance.gpsRequired': 'GPS erforderlich',
    'attendance.clockHint': 'Tippe auf die Schaltflache oben, um ein- oder auszustempeln.',
    'attendance.todayRecords': 'Heutige Eintrage',
    'attendance.dayStatus': 'Tagesstatus',
    'attendance.workedMinutes': 'Arbeitsminuten',
    'attendance.present': 'Anwesend',
    'attendance.absent': 'Abwesend',
    'attendance.late': 'Verspatet',
    'attendance.halfDay': 'Halber Tag',
    'attendance.leaveHoliday': 'Urlaub/Feiertag',
    'attendance.noCheckout': 'Kein Checkout',
    'attendance.pending': 'Ausstehend',
    'attendance.loadingCalendar': 'Kalender wird geladen...',
    'attendance.status': 'Status',
    'attendance.scanSiteQr': 'Standort-QR scannen',
    'attendance.scanSiteQrHint': 'Richte die Kamera auf den Standort-QR-Code.',
    'attendance.webQrUnavailable': 'Kamerascan ist im Web nicht verfugbar. Fuge den QR-Token ein.',
    'attendance.pasteQrToken': 'QR-Token einfugen',
    'attendance.useToken': 'Token verwenden',
    'attendance.preparingCamera': 'Kamera wird vorbereitet...',
    'attendance.cameraPermission': 'Kamerazugriff ist zum Scannen erforderlich.',
    'attendance.allowCamera': 'Kamera erlauben',
    'attendance.alignQr': 'QR-Code im Rahmen ausrichten',
    'attendance.loadingData': 'Anwesenheitsdaten werden geladen...',
    'attendance.refreshing': 'Wird aktualisiert...',
    'attendance.retrySync': 'Sync erneut versuchen',
    'attendance.locationUnavailableTitle': 'Standort nicht verfuegbar',
    'attendance.locationUnavailableMessage': 'Wir konnten deinen Standort nicht rechtzeitig abrufen. Moechtest du es erneut versuchen?',
    'attendance.invalidQr': 'Ungueltiger QR-Code. Bitte scanne den richtigen Standort-QR.',
    'attendance.qrValidationFailed': 'QR-Pruefung fehlgeschlagen. Bitte versuche es erneut.',
    'attendance.recordedWithWarnings': 'Anwesenheit mit Warnungen erfasst.',
    'attendance.recordedSuccessfully': 'Anwesenheit erfolgreich erfasst.',
    'attendance.locationRequiredError': 'Standort ist erforderlich, um Anwesenheit fuer diesen Standort zu erfassen.',
    'attendance.locationTimeoutError': 'Wir konnten deinen Standort nicht rechtzeitig abrufen. Bitte versuche es bei stabilem GPS erneut.',
    'attendance.loadError': 'Anwesenheit konnte nicht geladen werden. Bitte erneut versuchen.',
    'requests.title': 'Urlaubsanfragen',
    'requests.yourBalance': 'DEIN SALDO',
    'requests.requestHistory': 'ANFRAGEVERLAUF',
    'requests.noHistory': 'Kein Anfrageverlauf gefunden.',
    'requests.requestLeave': 'Urlaub beantragen',
    'requests.leaveType': 'Urlaubsart',
    'requests.selectType': 'Art auswahlen',
    'requests.startDate': 'Startdatum',
    'requests.endDate': 'Enddatum',
    'requests.medicalReportRequired': 'Medizinische Bericht-ID (Erforderlich)',
    'requests.enterDocumentId': 'Dokument-ID eingeben...',
    'requests.noteOptional': 'Notiz (Optional)',
    'requests.addNote': 'Notiz hinzufugen...',
    'requests.submitRequest': 'Anfrage senden',
    'requests.cancelRequest': 'Anfrage abbrechen',
    'requests.readMore': 'Mehr lesen',
    'requests.requestDetails': 'Anfragedetails',
    'requests.reason': 'Grund',
    'requests.noteFromApprover': 'Notiz des Genehmigers',
    'requests.dateRange': 'Zeitraum',
    'requests.status': 'Status',
    'requests.requestedDays': 'Angefragte Tage',
    'requests.createdAt': 'Erstellt',
    'requests.reviewedAt': 'Geprüft',
    'requests.validationTitle': 'Daten prüfen',
    'requests.datesRequiredError': 'Startdatum und Enddatum sind erforderlich.',
    'requests.startDatePastError': 'Das Startdatum darf nicht vor heute liegen.',
    'requests.endDateBeforeStartError': 'Das Enddatum darf nicht vor dem Startdatum liegen.',
    'requests.submitRequestError': 'Urlaubsanfrage konnte nicht gesendet werden. Bitte versuche es erneut.',
    'requests.cancelSuccessTitle': 'Anfrage abgebrochen',
    'requests.cancelSuccessMessage': 'Deine Urlaubsanfrage wurde erfolgreich abgebrochen.',
    'requests.cancelRequestError': 'Urlaubsanfrage konnte nicht abgebrochen werden. Bitte versuche es erneut.',
    'requests.cancelPayrollLockedError': 'Dieser Urlaub kann nicht abgebrochen werden, da die Gehaltsabrechnung für diesen Zeitraum bereits verarbeitet wurde.',
    'requests.cancelAlreadyStartedError': 'Dieser Urlaub kann nicht abgebrochen werden, da er bereits begonnen hat.',
    'requests.availableDays': 'Verfügbare Tage',
    'requests.vacation': 'Urlaub',
    'requests.sickLeave': 'Krankheit',
    'requests.personal': 'Persoenlicher Urlaub',
    'requests.unpaid': 'Unbezahlter Urlaub',
    'requests.parental': 'Elternzeit',
    'requests.other': 'Sonstiger Urlaub',
    'requests.companyPaidDays': 'Vom Unternehmen bezahlt',
    'requests.extraDays': 'extra (vom Gehalt abgezogen)',
    'requests.socialSecurityNote': 'Tage von der Sozialversicherung gedeckt',
    'requests.approved': 'Genehmigt',
    'requests.pending': 'Ausstehend',
    'requests.rejected': 'Abgelehnt',
    'requests.cancelled': 'Abgebrochen',
    'payroll.title': 'Gehaltslauf',
    'payroll.notIncluded': 'Gehaltslauf nicht enthalten',
    'payroll.upgradeText': 'Gehaltslauf ist in Growth- und Professional-Planen verfugbar. Upgrade auf worknest.com.',
    'payroll.current': 'Aktuell',
    'payroll.netPay': 'Netto',
    'payroll.cardHint': 'Tippen, um Gehaltsdetails anzuzeigen und die PDF herunterzuladen.',
    'payroll.details': 'Gehaltsdetails',
    'payroll.loadingDetails': 'Gehaltsdetails werden geladen...',
    'payroll.downloadPdf': 'Gehalts-PDF herunterladen',
    'payroll.downloading': 'Wird heruntergeladen...',
    'payroll.pdfUnavailable': 'PDF nicht verfugbar - Gehalt muss vor dem Download berechnet werden.',
    'updates.title': 'Ankundigungen',
    'updates.noAnnouncements': 'Noch keine Ankundigungen',
    'updates.announcement': 'Ankundigung',
    'updates.important': 'Wichtig',
    'updates.general': 'Allgemein',
    'updates.markAsRead': 'Als gelesen markieren',
    'updates.justNow': 'gerade eben',
    'updates.yesterday': 'gestern',
    'updates.minutesAgo': 'Min. her',
    'updates.hoursAgo': 'Std. her',
    'updates.daysAgo': 'Tage her',
    'updates.monthAgo': 'Monat her',
    'updates.monthsAgo': 'Monate her',
    'profile.employmentInformation': 'Beschaftigungsinformationen',
    'profile.department': 'Abteilung',
    'profile.site': 'Standort',
    'profile.contract': 'Vertrag',
    'profile.contractType': 'Vertragstyp',
    'profile.contractStatus': 'Vertragsstatus',
    'profile.contractStartDate': 'Vertragsbeginn',
    'profile.contractEndDate': 'Vertragsende',
    'profile.language': 'Sprache',
    'profile.selectLanguage': 'Sprache auswahlen',
    'profile.currentLanguage': 'Aktuelle Sprache',
    'profile.changePassword': 'Passwort andern',
    'profile.changePasswordSubtitle': 'Passwort aktualisieren',
    'profile.currentPassword': 'Aktuelles Passwort',
    'profile.newPassword': 'Neues Passwort',
    'profile.confirmNewPassword': 'Neues Passwort bestätigen',
    'profile.passwordRules': 'Passwortregeln',
    'profile.changePasswordSuccess': 'Passwort erfolgreich geändert!',
    'profile.changePasswordSuccessSubtitle': 'Ihr Passwort wurde erfolgreich aktualisiert.',
    'profile.updatingPassword': 'Passwort wird aktualisiert...',
    'profile.differentPasswordError': 'Das neue Passwort muss sich vom aktuellen Passwort unterscheiden.',
    'profile.passwordsMustMatch': 'Das neue Passwort und die Bestätigung müssen übereinstimmen.',
    'profile.allFieldsRequired': 'Alle Felder sind erforderlich.',
    'profile.logout': 'Abmelden',
    'employees.title': 'Mitarbeiter',
    'employees.subtitle': 'Verwalte deine Belegschaft hier.',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.welcomeBack': 'Willkommen zuruck',
    'auth.signInToContinue': 'Melde dich an, um fortzufahren',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.login': 'Anmelden',
    'auth.loggingIn': 'Anmeldung...',
    'auth.backToLogin': 'Zurueck zur Anmeldung',
    'auth.emailAddress': 'E-Mail-Adresse',
    'auth.emailPlaceholder': 'deine.email@firma.com',
    'auth.emailRequiredError': '* Bitte gib deine E-Mail-Adresse ein',
    'auth.forgotPasswordTitle': 'Passwort zuruecksetzen',
    'auth.forgotPasswordSubtitle': 'Wir senden dir einen Reset-Link per E-Mail',
    'auth.sendResetLink': 'Reset-Link senden',
    'auth.sending': 'Wird gesendet...',
    'auth.resetInstructionsSent': 'Wenn das Konto existiert, werden Anweisungen gesendet.',
    'auth.resetEmailFallbackError': 'Reset-E-Mail kann gerade nicht gesendet werden. Bitte versuche es erneut.',
    'auth.emailSentTitle': 'E-Mail erfolgreich gesendet!',
    'auth.emailSentSubtitle': 'Wir haben dir einen Link zum Zuruecksetzen des Passworts gesendet. Bitte pruefe deine E-Mail und folge den Anweisungen.',
    'auth.resetPasswordTitle': 'Passwort zuruecksetzen',
    'auth.resetPasswordSubtitle': 'Lege dein neues Passwort fest und melde dich erneut an.',
    'auth.resetToken': 'Reset-Token',
    'auth.resetTokenRequired': 'Reset-Token ist erforderlich.',
    'auth.newPassword': 'Neues Passwort',
    'auth.confirmPassword': 'Passwort bestaetigen',
    'auth.enterNewPassword': 'Neues Passwort eingeben',
    'auth.confirmNewPassword': 'Neues Passwort bestaetigen',
    'auth.passwordInvalid': 'Das Passwort ist ungueltig.',
    'auth.passwordMinLengthError': 'Das Passwort muss mindestens 8 Zeichen haben.',
    'auth.passwordUppercaseError': 'Das Passwort muss mindestens einen Grossbuchstaben enthalten.',
    'auth.passwordDigitError': 'Das Passwort muss mindestens eine Ziffer enthalten.',
    'auth.passwordEmailError': 'Das Passwort darf nicht deiner E-Mail entsprechen.',
    'auth.passwordMismatchError': 'Die Passwoerter stimmen nicht ueberein.',
    'auth.passwordRuleTitle': 'Das Passwort muss:',
    'auth.passwordRuleMinLength': 'Mindestens 8 Zeichen haben',
    'auth.passwordRuleUppercaseDigit': '1 Grossbuchstaben und 1 Ziffer enthalten',
    'auth.passwordRuleMatch': 'In beiden Feldern uebereinstimmen',
    'auth.resetting': 'Wird zurueckgesetzt...',
    'auth.resetSuccessMessage': 'Passwort erfolgreich zurueckgesetzt. Bitte melde dich mit dem neuen Passwort an.',
    'auth.requestNewLink': 'Neuen Link anfordern',
    'auth.createNewPasswordTitle': 'Neues Passwort erstellen',
    'auth.createNewPasswordSubtitle': 'Gib unten dein neues Passwort ein',
    'auth.updatePassword': 'Passwort aktualisieren',
    'auth.passwordUpdatedTitle': 'Passwort aktualisiert!',
    'auth.passwordUpdatedSubtitle': 'Dein Passwort wurde erfolgreich aktualisiert. Du kannst dich jetzt mit dem neuen Passwort anmelden.',
    'auth.linkExpiredTitle': 'Link abgelaufen!',
    'auth.linkExpiredSubtitle': 'Dieser Reset-Link ist abgelaufen. Bitte fordere einen neuen an.',
    'auth.sessionExpiredTitle': 'Sitzung abgelaufen!',
    'auth.sessionExpiredSubtitle': 'Deine Sitzung ist wegen Inaktivitaet abgelaufen. Bitte melde dich erneut an.',
    'auth.redirectingToLogin': 'Weiterleitung zur Anmeldung...',
    'auth.chooseWorkspace': 'Workspace waehlen',
    'auth.chooseWorkspaceSubtitle': 'Waehle die Rolle, die du in WorkNest Mobile verwenden moechtest.',
    'auth.noRoleAssignments': 'Keine Rollen verfuegbar. Bitte kontaktiere deinen Administrator.',
    'auth.select': 'Auswaehlen',
    'auth.invitationTokenTitle': 'Einladungs-Token',
    'auth.invitationToken': 'Einladungs-Token',
    'auth.invitationTokenRequired': 'Einladungs-Token ist erforderlich.',
    'auth.invitationPreflightSubtitle': 'Pruefe deine Einladung, bevor du dein Konto aktivierst.',
    'auth.validating': 'Wird geprueft...',
    'auth.validateInvitation': 'Einladung pruefen',
    'auth.tryAnotherToken': 'Anderen Token versuchen',
    'auth.continueToActivation': 'Weiter zur Aktivierung',
    'auth.activateInvitationTitle': 'Einladung aktivieren',
    'auth.activateInvitationSubtitle': 'Lege ein Passwort fest, gib deine Zustimmung und schliesse die Aktivierung ab.',
    'auth.invitationTokenMissing': 'Einladungs-Token fehlt.',
    'auth.gdprConsentRequired': 'GDPR-Zustimmung ist erforderlich.',
    'auth.preferredLanguageOptional': 'Bevorzugte Sprache (optional)',
    'auth.gdprConsent': 'Ich stimme der GDPR-Datenverarbeitung zu.',
    'auth.activating': 'Wird aktiviert...',
    'auth.activateInvitation': 'Einladung aktivieren',
    'auth.invitationActivatedTitle': 'Einladung aktiviert',
    'auth.invitationActivatedMessage': 'Dein Konto ist bereit. Bitte melde dich an, um fortzufahren.',
    'auth.error.invalidCredentials': 'Ungueltige E-Mail oder Passwort',
    'auth.error.accountLocked': 'Konto voruebergehend gesperrt. Versuche es spaeter erneut',
    'auth.error.noPlatformAccess': 'Dieses Konto hat keinen mobilen Zugriff',
    'auth.error.userPending': 'Dein Konto wartet auf Aktivierung',
    'auth.error.userSuspended': 'Dein Konto ist gesperrt',
    'auth.error.userDeactivated': 'Dein Konto ist deaktiviert',
    'auth.error.roleAssignmentNotFound': 'Die ausgewaehlte Rolle ist nicht mehr gueltig',
    'auth.error.roleAssignmentInactive': 'Die ausgewaehlte Rolle ist inaktiv',
    'auth.error.roleAssignmentForbidden': 'Du kannst auf diese Rolle nicht zugreifen',
    'auth.error.sessionExpired': 'Deine Sitzung ist abgelaufen. Bitte melde dich erneut an',
    'auth.error.accessDenied': 'Du bist fuer diese Aktion nicht berechtigt.',
    'auth.error.resetTokenInvalid': 'Dieser Reset-Link ist ungueltig. Fordere einen neuen Link an.',
    'auth.error.resetTokenExpired': 'Dieser Reset-Link ist abgelaufen. Fordere einen neuen Link an.',
    'auth.error.resetTokenAlreadyUsed': 'Dieser Reset-Link wurde bereits verwendet. Fordere einen neuen Link an.',
    'auth.error.invitationTokenInvalid': 'Dieser Einladungs-Token ist ungueltig. Fordere eine neue Einladung an.',
    'auth.error.invitationTokenExpired': 'Dieser Einladungs-Token ist abgelaufen. Fordere eine neue Einladung an.',
    'auth.error.invitationAlreadyUsed': 'Diese Einladung wurde bereits verwendet. Kontaktiere deinen Administrator.',
    'auth.error.unknown': 'Etwas ist schiefgelaufen. Bitte versuche es erneut.',
    'notifications.title': 'Benachrichtigungen',
    'notifications.newBadge': 'neu',
    'notifications.leaveApproved': 'Urlaubsanfrage genehmigt',
    'notifications.payslipReady': 'Gehaltsabrechnung bereit',
    'notifications.newAnnouncement': 'Neue Ankündigung',
    'notifications.leaveRejected': 'Urlaubsanfrage abgelehnt',
    'notifications.leaveApprovedMessage': 'Deine Urlaubsanfrage wurde genehmigt.',
    'notifications.leaveRejectedMessage': 'Deine Urlaubsanfrage wurde abgelehnt.',
    'notifications.leaveRejectedReason': 'Grund',
    'notifications.empty': 'Noch keine Benachrichtigungen',
    'notifications.error': 'Benachrichtigungen konnten nicht geladen werden',
    'notifications.loading': 'Benachrichtigungen werden geladen...',
  },
};

interface LocalizationContextValue {
  language: LanguageCode;
  languageLabel: string;
  languages: LanguageOption[];
  setLanguage: (language: LanguageCode) => Promise<void>;
  t: (key: TranslationKey) => string;
}

const LocalizationContext = createContext<LocalizationContextValue | null>(null);

function isLanguageCode(value: string | null): value is LanguageCode {
  return LANGUAGES.some((language) => language.code === value);
}

export function LocalizationProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>('en');

  useEffect(() => {
    let isMounted = true;

    SecureStore.getItemAsync(LANGUAGE_STORAGE_KEY)
      .then((storedLanguage) => {
        if (isMounted && isLanguageCode(storedLanguage)) {
          setLanguageState(storedLanguage);
        }
      })
      .catch(() => {
        // Keep English when stored language cannot be read.
      });

    return () => {
      isMounted = false;
    };
  }, []);

  const setLanguage = useCallback(async (nextLanguage: LanguageCode) => {
    setLanguageState(nextLanguage);
    await SecureStore.setItemAsync(LANGUAGE_STORAGE_KEY, nextLanguage);
  }, []);

  const t = useCallback(
    (key: TranslationKey) => translations[language][key] ?? translations.en[key] ?? key,
    [language]
  );

  const value = useMemo(
    () => ({
      language,
      languageLabel: LANGUAGES.find((item) => item.code === language)?.label ?? LANGUAGES[0].label,
      languages: LANGUAGES,
      setLanguage,
      t,
    }),
    [language, setLanguage, t]
  );

  return (
    <LocalizationContext.Provider value={value}>
      {children}
    </LocalizationContext.Provider>
  );
}

export function useLocalization() {
  const context = useContext(LocalizationContext);

  if (!context) {
    throw new Error('useLocalization must be used within LocalizationProvider');
  }

  return context;
}
